
package org.oasis_open.docs.ws_tx.wscoor._2006._06;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistrationResponseService", targetNamespace = "http://docs.oasis-open.org/ws-tx/wscoor/2006/06", wsdlLocation = "wsdl/wscoor-registration-response-binding.wsdl")
public class RegistrationResponseService
    extends Service
{

    private final static URL REGISTRATIONRESPONSESERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONRESPONSESERVICE_EXCEPTION;
    private final static QName REGISTRATIONRESPONSESERVICE_QNAME = new QName("http://docs.oasis-open.org/ws-tx/wscoor/2006/06", "RegistrationResponseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("wsdl/wscoor-registration-response-binding.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONRESPONSESERVICE_WSDL_LOCATION = url;
        REGISTRATIONRESPONSESERVICE_EXCEPTION = e;
    }

    public RegistrationResponseService() {
        super(__getWsdlLocation(), REGISTRATIONRESPONSESERVICE_QNAME);
    }

    public RegistrationResponseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONRESPONSESERVICE_QNAME, features);
    }

    public RegistrationResponseService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONRESPONSESERVICE_QNAME);
    }

    public RegistrationResponseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONRESPONSESERVICE_QNAME, features);
    }

    public RegistrationResponseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationResponseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistrationResponsePortType
     */
    @WebEndpoint(name = "RegistrationResponsePortType")
    public RegistrationResponsePortType getRegistrationResponsePortType() {
        return super.getPort(new QName("http://docs.oasis-open.org/ws-tx/wscoor/2006/06", "RegistrationResponsePortType"), RegistrationResponsePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationResponsePortType
     */
    @WebEndpoint(name = "RegistrationResponsePortType")
    public RegistrationResponsePortType getRegistrationResponsePortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ws-tx/wscoor/2006/06", "RegistrationResponsePortType"), RegistrationResponsePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONRESPONSESERVICE_EXCEPTION!= null) {
            throw REGISTRATIONRESPONSESERVICE_EXCEPTION;
        }
        return REGISTRATIONRESPONSESERVICE_WSDL_LOCATION;
    }

}
