
:sectnums!: all

[appendix]
= Object store implementations

== The ObjectStore

This appendix examines the various ArjunaCore object store implementations and gives guidelines for creating other implementations and plugging into an application.

This release of {productName} contains several different implementations of a basic object store.
Each serves a particular purpose and is generally optimized for that purpose.
Each of the implementations implements the `ObjectStoreAPI` interface, which defines the minimum operations which must be provided for an object store implementation to be used by the Transaction Service.
You can override the default object store implementation at runtime by setting the `com.arjuna.ats.arjuna.objectstore.objectStoreType` property variable to one of the types described below.

.Class `StateStatus`
[source,java]
----
include::{projectSourceDir}/appendix/extras/appendix_StateStatus.java[]
----

{productName} programmers do not usually need to interact with any of the object store implementations directly, apart from possibly creating them in the first place.
Even this is not necessary if the default store type is used, since {productName} creates stores as necessary.
All stores manipulate instances of the class `ObjectState`.
These instances are named using a `type` (via the object's `type()` operation) and a [path]_Uid_ .

For atomic actions purposes, object states in the store can be principally in two distinct states: `OS_COMMITTED` or `OS_UNCOMMITTED`.
An object state starts in the `OS_COMMITTED` state, but when it is modified under the control of an atomic action, a new second object state may be written that is in the `OS_UNCOMMITTED` state.
If the action commits, this second object state replaces the original and becomes `OS_COMMITTED`.
If the action aborts, this second object state is discarded.
All of the implementations provided with this release handle these state transitions by making use of shadow copies of object states.
However, any other implementation that maintains this abstraction is permissible.

Object states may become hidden, and thus inaccessible, under the control of the crash recovery system.

You can browse the contents of a store through the `allTypes` and `allObjUids` operations. `allTypes` returns an `InputObjectState` containing all of the type names of all objects in a store, terminated by a `null` name.
`allObjUids` returns an `InputObjectState` containing all of the `Uids` of all objects of a given type, terminated by the special `Uid.nullUid()`.

=== Persistent object stores

This section briefly describes the characteristics and optimizations of each of the supplied implementations of the persistent object store.
Persistent object states are mapped onto the structure of the file system supported by the host operating system.

==== Common functionality

In addition to the features mentioned earlier, all of the supplied persistent object stores obey the following rules:

* Each object state is stored in its own file, which is named using the Uid of the object.
* The type of an object, as given by the `type()` operation, determines the directory into which the object is placed.
* All of the stores have a common root directory that is determined when {productName} is configured.
This directory name is automatically prepended to any store-specific root information.
* All stores also have the notion of a localized root directory that is automatically prepended to the type of the object to determine the ultimate directory name.
The localized root name is specified when the store is created.
The default name is `defaultStore`.

[source,text]
----
include::{projectSourceDir}/appendix/extras/default_layout.txt[]
----

==== The shadowing store

The shadowing store is the original version of the object store, which was provided in prior releases.
It is implemented by the class `ShadowingStore`.
It is simple but slow.
It uses pairs of files to represent objects.
One file is the shadow version and the other is the committed version.
Files are opened, locked, operated upon, unlocked, and closed on every interaction with the object store.
This causes a lot of I/O overhead.

If you are overriding the object store implementation, the type of this object store is `ShadowingStore`.

==== No file-level locking

Since transactional objects are concurrency-controlled through `LockManager`, you do not need to impose additional locking at the file level.
The basic ShadowingStore implementation handles file-level locking.
Therefore, the default object store implementation for {productName}, [path]_ShadowNoFileLockStore_, relies upon user-level locking.
This enables it to provide better performance than the [path]_ShadowingStore_ implementation.

If you are overriding the object store implementation, the type of this object store is `ShadowNoFileLockStore`.

==== The hashed store

The HashedStore has the same structure for object states as the ShadowingStore, but has an alternate directory structure that is better suited to storing large numbers of objects of the same type.
Using this store, objects are scattered among a set of directories by applying a hashing function to the object's Uid.
By default, 255 sub-directories are used.
However, you can override this by setting the `ObjectStoreEnvironmentBean.hashedDirectories` environment variable accordingly.

If you are overriding the object store implementation, the type of this object store is `HashedStore`.

==== The JDBC store

The JDBCStore uses a JDBC database to save persistent object states.
When used in conjunction with the Transactional Objects for Java API, nested transaction support is available.
In the current implementation, all object states are stored as [term]_Binary Large Objects (BLOBs)_ within the same table.
The limitation on object state size imposed by using BLOBs is `64k`.
If you try to store an object state which exceeds this limit, an error is generated and the state is not stored.
The transaction is subsequently forced to roll back.

When using the JDBC object store, the application must provide an implementation of the `JDBCAccess` interface, located in the `com.arjuna.ats.arjuna.objectstore` package:

.Interface `JDBCAccess`
[source,java]
----
include::{projectSourceDir}/appendix/extras/jdbcaccess.java[]
----

The implementation of this class is responsible for providing the `Connection` which the JDBC ObjectStore uses to save and restore object states:

`getConnection`::
Returns the Connection to use.
This method is called whenever a connection is required, and the implementation should use whatever policy is necessary for determining what connection to return.
This method need not return the same `Connection` instance more than once.

putConnection::
Returns one of the `Connections` acquired from `getConnection`.
Connections are returned if any errors occur when using them.

initialise::
Used to pass additional arbitrary information to the implementation.

The JDBC object store initially requests the number of `Connections` defined in the `ObjectStoreEnvironmentBean.jdbcPoolSizeInitial` property and will use no more than defined in the `ObjectStoreEnvironmentBean.jdbcPoolSizeMaximum` property.

The implementation of the `JDBCAccess` interface to use should be set in the `ObjectStoreEnvironmentBean.jdbcUserDbAccessClassName` property variable.

If overriding the object store implementation, the type of this object store is `JDBCStore`.

A JDBC object store can be used for managing the transaction log.
In this case, the transaction log implementation should be set to `JDBCActionStore` and the `JDBCAccess` implementation must be provided via the `ObjectStoreEnvironmentBean.jdbcTxDbAccessClassName` property variable.
In this case, the default table name is [path]_JBossTSTxTable_ .

You can use the same `JDBCAccess` implementation for both the user object store and the transaction log.

==== The cached store

This object store uses the hashed object store, but does not read or write states to the persistent backing store immediately.
It maintains the states in a volatile memory cache and either flushes the cache periodically or when it is full.
The failure semantics associated with this object store are different from the normal persistent object stores, because a failure could result in states in the cache being lost.

If overriding the object store implementation, the type of this object store is `CacheStore`.

.Configuration Properties
ObjectStoreEnvironmentBean.cacheStoreHash::
sets the number of internal stores to hash the states over.
The default value is 128.

ObjectStoreEnvironmentBean.cacheStoreSize::
the maximum size the cache can reach before a flush is triggered.
The default is 10240 bytes.

ObjectStoreEnvironmentBean.cacheStoreRemovedItems::
the maximum number of removed items that the cache can contain before a flush is triggered.
By default, calls to remove a state that is in the cache will simply remove the state from the cache, but leave a blank entry (rather than remove the entry immediately, which would affect the performance of the cache).
When triggered, these entries are removed from the cache.
The default value is twice the size of the hash.

ObjectStoreEnvironmentBean.cacheStoreWorkItems::
the maximum number of items that are allowed to build up in the cache before it is flushed.
The default value is 100.
`ObjectStoreEnvironmentBean.cacheStoreScanPeriod` sets the time in milliseconds for periodically flushing the cache.
The default is 120 seconds.

ObjectStoreEnvironmentBean.cacheStoreSync::
determines whether flushes of the cache are sync-ed to disk.
The default is `OFF`.
To enable, set to `ON`.

==== LogStore

This implementation is based on a traditional transaction log.
All transaction states within the same process (VM instance) are written to the same log (file), which is an append-only entity.
When transaction data would normally be deleted, at the end of the transaction, a [path]_delete_ record is added to the log instead.
Therefore, the log just keeps growing.
Periodically a thread runs to prune the log of entries that have been deleted.

A log is initially given a maximum capacity beyond which it cannot grow.
After it reaches this size, the system creates a new log for transactions that could not be accommodated in the original log.
The new log and the old log are pruned as usual.
During the normal execution of the transaction system, there may be an arbitrary number of log instances.
These should be garbage collected by the system,(or the recovery sub-system, eventually.

Check the Configuration Options table for how to configure the LogStore.

=== Clustered and Persistent object stores
==== InfinispanSlotStore

[WARNING]
====
This is an experimental feature. It is not recommended for production systems and may contain breaking changes in future releases. If the store is enabled on startup you should notice a warning message in the logs:

`ARJUNA012419: InfinispanSlotStore: Initializing experimental feature. Do not use in production.`
====

With this store, transaction logs are stored in an infinispan cache. The user is responsible for configuring the cache in such a way that the store can serve as transaction log storage, for example cache writes should be backed by persistent storage so that they can be recovered in the event of the loss of all nodes hosting the cache.

The InfinispanSlotStore is implemented internally using the Narayana SlotStore feature whose design is conceptually an array. The SlotStore is divided into a number of elements, each capable of holding one entry of up to a given size. The SlotStore has pluggable sub-implementations, termed backends, and the InfinispanSlotStore is one such backend.

.Configuration Properties

ObjectStoreEnvironmentBean.objectStoreType::
Defines the object store implementation and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.SlotStoreAdaptor`.
As is usual with most object store types, it is recommended to also set the state and communication stores to the same type, ie `ObjectStoreEnvironmentBean.stateStore.objectStoreType` and `ObjectStoreEnvironmentBean.communicationStore.objectStoreType`
properties.

SlotStoreEnvironmentBean.backingSlotsClassName::
Defines the SlotStore backend and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.infinispan.InfinispanSlots` to enable the feature.

SlotStoreEnvironmentBean.numberOfSlots::
Sets the desired number of slots for the store.
Should equal the maximum number of unresolved transactions expected at any given time,
including those in-flight and awaiting recovery.
[WARNING]
====
Caution: reducing the number of slots in a non-empty store may result in data loss.
====
The default is 256.

SlotStoreEnvironmentBean.bytesPerSlot::
Sets the desired maximum size of entries in the store. A typical transaction record is less than 1KB.
The optimum sizing depends on both the infinispan storage and whether write-through caches are used (which they should be for transaction logs).
[WARNING]
====
Modifying the size of slots in a non-empty store may result in data loss.
====
Default: 4096

InfinispanStoreEnvironmentBean.infinispanConfigFileName::
The infinispan xml based cache configuration. The config file name relative to the resource directory
so begins with a slash char
[[NOTE]]
====
Properties set in this infinispan xml config file will override any related config the beans, including 
`cacheName`, `nodeAddress`, `storeDir` and `groupName`.
====
Default: /infinispan-config.xml

InfinispanStoreEnvironmentBean.cacheName::
The name of the cache used to store the key/value pairs for this slot store

Default: clusteredObjectStore

InfinispanStoreEnvironmentBean.cache::
Set the infinispan cache that the InfinispanSlotStore should use.

InfinispanStoreEnvironmentBean.storeDir::
When infinispan write through caching is configured set the filesystem location used for the storage.
If storeDir is not an absolute path then it will be interpreted as being relative to the User's current working directory
(as defined by the user.dir system property).

[WARNING]
====
This setting only applies for programmatic configuration of the cache. If `infinispanConfigFileName` is configured then the cache config will use that file instead.
====
Default: infinispan-caches

InfinispanStoreEnvironmentBean.ignoreReturnValues::
When set to true the return value of cache write operations will be ignored to avoid needless remote calls.
Default: true

InfinispanStoreEnvironmentBean.nodeAddress::
The address of the node within a cluster.
Used in clustered and embedded scenarios to identify which member of the JGroups cluster
the JVM is currently representing.

InfinispanStoreEnvironmentBean.groupName::
== Cluster Configuration Considerations
1. A single member must run the recovery manager and a new one started if it fails (aka an HA singleton)
2. Top down recovery via the AtomicActionRecoveryModule will recover all transactions in the store unless the
recovery groupName is set in which case the recovery manager will only recover AtomicActions created
with that groupName.
3. Any member can create and commit transactions ({@link com.arjuna.ats.arjuna.recovery.TransactionStatusManager}
will be used during recovery to decide if the creator is still running)
<p>
The group name may also be used in Distributed Mode which can provide orders of magnitude improvements in
scalability than can the Replication Mode. For example if a large cluster is supporting multi-tenancy
(multiple transaction and recovery managers) then Distributed Mode together with key grouping can ensure
that cache entries for a particular group are co-located on a group of cluster nodes rather than being
scattered over the entire cluster.

leave unset if group name functionality is not required

InfinispanStoreEnvironmentBean.slotKeyGeneratorClassName::
The classname of the class that should be used to generate unique slot keys. The class should implement the interface
`com.arjuna.ats.internal.arjuna.objectstore.slot.infinispan.InfinispanSlotKeyGenerator`.
If unset then a strategy based on `com.arjuna.ats.arjuna.common.Uid` will be used.

==== JGroupsSlotStore

The JGroupsSlotStore provides a clustered object store backed by JGroups ReplCache to replicate object states across cluster members.
Reads are served from the in-memory cache, providing low latency access.
This store combines high performance in-memory replication with configurable durability guarantees based on a write-ahead log (WAL) for persistence and for single node operation.
Like the Journal store, the write-ahead log is based on the Artemis Journal.

The implementation is built on the Narayana SlotStore framework and is configured as a backend to the SlotStoreAdaptor.

[WARNING]
====
This is an experimental feature. It is not recommended for production systems and may contain breaking changes in future releases. If the store is enabled on startup you should notice a warning message in the logs:

`ARJUNA012421: JGroupsSlotStore: Initializing experimental feature. Do not use in production.`
====

.Configuration Properties

ObjectStoreEnvironmentBean.objectStoreType::
Defines the object store implementation and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.SlotStoreAdaptor`.
It is recommended to also set the state and communication stores to the same type via `ObjectStoreEnvironmentBean.stateStore.objectStoreType` and `ObjectStoreEnvironmentBean.communicationStore.objectStoreType` properties.

SlotStoreEnvironmentBean.backingSlotsClassName::
Defines the SlotStore backend and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.jgroups.JGroupsSlots` to enable the feature.

SlotStoreEnvironmentBean.numberOfSlots::
Sets the number of slots for the store.
Should equal the maximum number of unresolved transactions expected at any given time, including those in-flight and awaiting recovery.
[WARNING]
====
Reducing the number of slots in a non-empty store may result in data loss.
====
The default is 256.

SlotStoreEnvironmentBean.bytesPerSlot::
Sets the maximum size of entries in the store.
A typical transaction record is less than 1KB.
[WARNING]
====
Modifying the size of slots in a non-empty store may result in data loss.
====
Default: 4096

JGroupsStoreEnvironmentBean.nodeAddress::
The address of the node within a cluster.
Used to identify which member of the JGroups cluster the JVM is currently representing.
This property has no default and must be set.
For single node clusters a good choice is CoreEnvironmentBean#getNodeIdentifier().

JGroupsStoreEnvironmentBean.clusterName::
The name of the JGroups cluster to join.
Default: "defaultJGroupsClusterName"

JGroupsStoreEnvironmentBean.cacheName::
The name of the ReplCache instance used to store transaction states.
Each object store type (transaction log, state store, communication store) should use a unique cache name.
Default: "defaultJGroupsCache"

JGroupsStoreEnvironmentBean.jGroupsConfigFileName::
The JGroups XML configuration file for the transport stack.
Default: "jgroups-transport-config.xml"

JGroupsStoreEnvironmentBean.replicationCount::
The number of cluster members to which each entry should be replicated.
Use `-1` for full replication to all cluster members.
With `1` the element is stored on a single node only, determined through consistent hashing.
Default: -1 (full replication)

JGroupsStoreEnvironmentBean.cachingTime::
The time in milliseconds to cache entries in a secondary L2 cache.
Set to `0` to disable L2 caching (recommended for consistency).
Default: 0 (disabled)

JGroupsStoreEnvironmentBean.callTimeout::
The maximum time in milliseconds a cache operation (such as a replicated put) will wait for responses from other nodes before aborting.
Default: 1500

JGroupsStoreEnvironmentBean.migrateData::
Whether to automatically migrate or re-replicate data entries to other nodes in the cluster when nodes join or leave.
Default: true

JGroupsStoreEnvironmentBean.slotKeyGeneratorClassName::
The classname of the class that should be used to generate unique slot keys.
The class must implement `com.arjuna.ats.internal.arjuna.objectstore.slot.jgroups.JGroupsSlotKeyGenerator`.
If unset then a strategy based on `com.arjuna.ats.arjuna.common.Uid` will be used.

JGroupsStoreEnvironmentBean.walEnabled::
Enables the write-ahead log for persistence.
When enabled, all writes are persisted to disk using an Artemis Journal before being applied to the ReplCache.
Must be set to true for transaction types with durability guarantees.
Default: true

JGroupsStoreEnvironmentBean.storeDir::
The filesystem location for the write-ahead log files.
If not an absolute path, it is interpreted relative to the user's current working directory.
Only applies when `walEnabled` is true.
Default: "$user.dir/SlotStore"

JGroupsStoreEnvironmentBean.walSyncWrites::
When true, write operations are immediately flushed to disk (fsync) — recommended for transaction types with durability guarantees.
When false, writes are buffered and flushed periodically.
Only applies when `walEnabled` is true.
Default: true

JGroupsStoreEnvironmentBean.walSyncDeletes::
When true, delete operations are immediately flushed to disk.
When false, deletes are buffered which in total failure scenarios can result in warnings (because the transaction manager will think they are still in doubt).
Only applies when `walEnabled` is true.
Default: true

JGroupsStoreEnvironmentBean.walBufferSize::
The size in bytes of the write buffer for the write-ahead log.
Larger buffers allow more batching but use more memory.
Only applies when `walEnabled` is true.
Default: 501760 (490KB)

JGroupsStoreEnvironmentBean.walBufferFlushesPerSecond::
The number of times per second the write-ahead log buffer is flushed to disk.
Higher values reduce latency but may reduce throughput.
Only applies when `walEnabled` is true.
Default: 500

JGroupsStoreEnvironmentBean.walFileSize::
The desired size in bytes of each write-ahead log journal file.
Only applies when `walEnabled` is true.
Default: 2097152 (2MB)

JGroupsStoreEnvironmentBean.walMinFiles::
The minimum number of write-ahead log journal files to use.
Only applies when `walEnabled` is true.
Default: 2

JGroupsStoreEnvironmentBean.walPoolSize::
The upper limit for pre-created journal files.
Only applies when `walEnabled` is true.
Default: 0

JGroupsStoreEnvironmentBean.walCompactMinFiles::
The minimal number of files before write-ahead log compaction can be considered.
Only applies when `walEnabled` is true.
Default: 0

JGroupsStoreEnvironmentBean.walCompactPercentage::
The percentage minimum capacity usage at which to start write-ahead log compaction.
Only applies when `walEnabled` is true.
Default: 0

JGroupsStoreEnvironmentBean.walFilePrefix::
The prefix used when naming each write-ahead log journal file.
Only applies when `walEnabled` is true.
Default: "slot-journal"

JGroupsStoreEnvironmentBean.walFileExtension::
The suffix used when naming each write-ahead log journal file.
Only applies when `walEnabled` is true.
Default: "log"

JGroupsStoreEnvironmentBean.walMaxIO::
The maximum write requests queue depth for the write-ahead log.
For NIO this has no effect and is hard coded to 1. For AIO, the recommended value is 500.
Only applies when `walEnabled` is true.
Default: 2

JGroupsStoreEnvironmentBean.walAsyncIO::
Whether to use AIO (async I/O) for the write-ahead log journal.
Falls back silently to NIO if AIO native libraries are not available.
Only applies when `walEnabled` is true.
Default: false (NIO)

.Performance Considerations

With write-ahead log enabled and fsync (`walEnabled=true`, `walSyncWrites=true`, the default):

* Durability means the logs survive process crashes and power failures
* Reads are still served from the in-memory cache
* Write-ahead log provides recovery capability from cold starts

With write-ahead log disabled (`walEnabled=false`):

* Faster throughput but no local persistence
* Object states are only in memory but are still replicated across the cluster
* Crash recovery relies on other cluster members
* Not suitable for transaction types that require durability guarantees.

.Cluster Configuration Considerations

1. For transaction logs with durability requirements, enable write-ahead logging on at least one cluster member
2. A single member must run the recovery manager (HA singleton pattern)
3. Any member can create and commit transactions
4. The `TransactionStatusManager` is used during recovery to determine if the transaction creator is still running
5. In production, configure JGroups for your network topology (refer to the JGroups documentation for more detail)

==== JGroupsRaftSlotStore

The JGroupsRaftSlotStore provides a clustered transaction log store using the Raft consensus protocol for write operations.
This implementation is built on JGroups-Raft (for an overview see https://research.redhat.com/blog/2024/03/20/correctness-in-distributed-systems-the-case-of-jgroups-raft/) and ensures that all write operations are replicated to a majority of cluster members before being acknowledged.

Unlike JGroupsSlotStore which uses ReplCache for simple replication, this store uses Raft consensus so that every write must be acknowledged by a majority of Raft members before being considered committed.
Reads, however, are served from each node's local in-memory state machine and may return stale data.

Like the other slot-based stores, this implementation is built on the Narayana SlotStore framework and is configured as a backend to the SlotStoreAdaptor.

[WARNING]
====
This is an experimental feature. It is not recommended for production systems and may contain breaking changes in future releases. If the store is enabled on startup you should notice a warning message in the logs:

`ARJUNA012424: JGroupsRaftSlotStore: Initializing experimental feature. Do not use in production.`
====

.Configuration Properties

ObjectStoreEnvironmentBean.objectStoreType::
Defines the object store implementation and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.SlotStoreAdaptor`.
It is recommended to also set the state and communication stores to the same type via `ObjectStoreEnvironmentBean.stateStore.objectStoreType` and `ObjectStoreEnvironmentBean.communicationStore.objectStoreType` properties.

SlotStoreEnvironmentBean.backingSlotsClassName::
Defines the SlotStore backend and must be set to `com.arjuna.ats.internal.arjuna.objectstore.slot.jgroups.JGroupsRaftSlots` to enable the feature.

SlotStoreEnvironmentBean.numberOfSlots::
Sets the number of slots for the store.
Should equal the maximum number of unresolved transactions expected at any given time, including those in-flight and awaiting recovery.
[WARNING]
====
Reducing the number of slots in a non-empty store may result in data loss.
====
The default is 256.

SlotStoreEnvironmentBean.bytesPerSlot::
Sets the maximum size of entries in the store.
A typical transaction record is less than 1KB.
[WARNING]
====
Modifying the size of slots in a non-empty store may result in data loss.
====
Default: 4096

JGroupsStoreEnvironmentBean.nodeAddress::
The address of the node within a cluster.
Used as the Raft member ID (`raft_id`) and must be unique across all cluster members.
This property has no default and must be set.
For single node clusters a good choice is CoreEnvironmentBean#getNodeIdentifier().

JGroupsStoreEnvironmentBean.clusterName::
The name of the JGroups cluster to join.
All nodes in the Raft cluster must use the same cluster name.
Default: "defaultJGroupsClusterName"

JGroupsStoreEnvironmentBean.jGroupsConfigFileName::
The JGroups XML configuration file.
The stack must include the RAFT, ELECTION, NO_DUPES, and REDIRECT protocols.
Default: "jgroups-transport-config.xml"

JGroupsStoreEnvironmentBean.storeDir::
The filesystem location for the Raft persistent log files.
If not an absolute path, it is interpreted relative to the user's current working directory.
The Raft log stores the replicated state machine operations and is essential for crash recovery.
Default: "$user.dir/SlotStore"

JGroupsRaftStoreEnvironmentBean.raftMembers::
Optional comma-separated list of Raft member identifiers.
Example: "node1,node2,node3"
When set, all cluster members must have the same `raftMembers` configuration for the cluster to form correctly.
When omitted, the node auto-discovers an existing cluster and joins it via the REDIRECT protocol.
If no existing cluster is found, the node bootstraps as a single-member cluster.
On restart, membership is restored from the persistent Raft log regardless of this setting.
Use `JGroupsRaftSlots.addServer(name)` / `removeServer(name)` to modify membership at runtime.

JGroupsRaftStoreEnvironmentBean.raftLogFsync::
When true, Raft log entries are immediately flushed to disk (fdatasync).
When false, log entries are buffered and flushed periodically.
[WARNING]
====
Setting to false may improve performance but could result in data loss on power failure.
For production deployments requiring full durability, keep the default of true.
====
Default: true

JGroupsRaftStoreEnvironmentBean.raftTimeout::
The timeout in milliseconds for Raft operations.
This is the time to wait for a majority of group members to acknowledge a write operation.
Adjust based on network latency and cluster size.
Default: 5000 (5 seconds)

JGroupsRaftStoreEnvironmentBean.raftElectionMaxInterval::
The maximum time in milliseconds to wait for leader election during initialization.
If no leader is elected within this interval, initialization fails.
Default: 500

JGroupsRaftStoreEnvironmentBean.allowDirtyReads::
When true, reads are served from the node's local in-memory state machine without Raft consensus.
This is faster but may return stale data on follower nodes that have not yet received the latest log entries.
When false, reads go through the Raft leader for consistent results at the cost of higher latency.
Default: true

NOTE: Raft protocol-level heartbeat intervals and election min timeout are configured in the JGroups
XML configuration file via the `ELECTION` and `RAFT` protocol attributes. The election maximum interval
can be set either in JGroups XML or via `JGroupsRaftStoreEnvironmentBean.raftElectionMaxInterval`.

.Performance Characteristics

With Raft log fsync (`raftLogFsync=true`, the default):

- Full durability with majority consensus
- Survives both process crashes and power failures on majority of nodes
- Reduced performance due to disk sync

With Raft log buffered (`raftLogFsync=false`):

- Higher throughput due to reduced disk I/O
- Raft ensures majority consensus before acknowledging writes
- May lose last few milliseconds of operations on power failure

.Consensus and Recovery Guarantees

1. **Raft Majority Consensus**: Every write operation is replicated to a majority of cluster members before being acknowledged
2. **Leader Election**: If the Raft leader fails, remaining members automatically elect a new leader
3. **Log Replication**: The Raft log is replicated to a majority and propagated to other members as they catch up and provides the source of truth for recovery
4. **Split-Brain Protection**: Raft's consensus mechanism prevents split-brain scenarios
5. **Reads**: Reads are served from each node's local in-memory state machine (dirty reads) and may return data that has not yet been replicated from the leader. Writes are strongly consistent; reads are eventually consistent.

.Cluster Configuration Considerations

1. **Odd Number of Members**: Deploy with an odd number of members and at least three for optimal fault tolerance:

   - 3 members: tolerates 1 failure
   - 5 members: tolerates 2 failures
   - 7 members: tolerates 3 failures

2. **Static vs Dynamic Membership**: Use `raftMembers` for a fixed cluster, or omit it for auto-discovery. When `raftMembers` is omitted, a node joins an existing cluster via the REDIRECT protocol or bootstraps as a single-member cluster if none exists. Use `addServer()`/`removeServer()` to grow or shrink the cluster at runtime
3. **Network Requirements**: Members must be able to communicate directly for leader election and heartbeats
4. **Recovery Manager**: Only one member should run the recovery manager to avoid duplicate recovery attempts
5. **Performance vs Durability**: Balance `raftLogFsync` setting based on durability requirements and acceptable performance
6. **Log Maintenance**: Raft log grows over time and may require periodic compaction (automatic in JGroups-Raft)

.When to Choose Raft over ReplCache

Use JGroupsRaftSlotStore when:

- Strong consistency guarantees are required
- Protection against split-brain scenarios is critical
- Automatic leader election and failover is needed
- You can tolerate higher write latency for stronger guarantees

Use JGroupsSlotStore (ReplCache) when:

- Maximum performance is the priority
- The cluster is deployed on a network where partitions are unlikely (e.g., a single rack or availability zone)
- Cluster membership is relatively stable

WARNING: ReplCache has no quorum mechanism. In a network partition, both sides accept writes independently with no conflict resolution on merge. For a transaction log store this can mean silently lost records. If split-brain protection is needed, use JGroupsRaftSlotStore instead.

:sectnums:
