
= Introduction

The _XML Transaction Service (XTS)_ component of {productName} supports the coordination of private and public Web Services in a business transaction.
Therefore, to understand XTS, you must be familiar with Web Services, and also understand something about transactions.
This chapter introduces XTS and provides a brief overview of the technologies that form the Web Services standard.
Additionally, this chapter explores some of the fundamentals of transactioning technology and how it can be applied to Web Services.
Much of the content presented in this chapter is detailed throughout this guide.
However, only overview information about Web Services is provided.
If you are new to creating Web services, please consult your Web Services platform documentation.

{productName} provides the XTS component as a transaction solution for Web Services.
Using XTS, business partners can coordinate complex business transactions in a controlled and reliable manner.
The XTS API supports a transactional coordination model based on the _WS-Coordination_, _WS-Atomic Transaction_, and _WS-Business Activity_ specifications.

.Protocols Included in XTS* WS-Coordination (WS-C) is a generic coordination framework developed by IBM, Microsoft and BEA.
* WS-Atomic Transaction (WS-AT) and WS-Business Activity (WS-BA) together comprise the WS-Transaction (WS-T) transaction protocols that utilize this framework.

{productName} implements versions 1.1, and 1.2 of these three specifications.
Version specifications are available from http://www.oasis-open.org/specs/ .

[NOTE]
====
The 1.1, and 1.2 specifications only differ in a small number of details.
The rest of this document employs version 1.1 of these specifications when providing explanations and example code.
On the few occasions where the modifications required to adapt these to the 1.1 specifications are not obvious, an explanatory note is provided.
====

_Web Services_ are modular, reusable software components that are created by exposing business functionality through a Web service interface.
Web Services communicate directly with other Web Services using standards-based technologies such as SOAP and HTTP.
These standards-based communication technologies enable customers, suppliers, and trading partners to access Web Services, independent of hardware operating system, or programming environment.
The result is a vastly improved collaboration environment as compared to today's EDI and _business-to-business (B2B)_ solutions, an environment where businesses can expose their current and future business applications as Web Services that can be easily discovered and accessed by external partners.

Web Services, by themselves, are not fault-tolerant.
In fact, some of the reasons that the Web Services model is an attractive development solution are also the same reasons that service-based applications may have drawbacks.

.Properties of Web Services
* Application components that are exposed as Web Services may be owned by third parties, which provides benefits in terms of cost of maintenance, but drawbacks in terms of having exclusive control over their behavior.
* Web Services are usually remotely located, increasing risk of failure due to increased network travel for invocations.

Applications that have high dependability requirements need a method of minimizing the effects of errors that may occur when an application consumes Web Services.
One method of safeguarding against such failures is to interact with an application's Web Services within the context of a _transaction_.
A transaction is a unit of work which is completed entirely, or in the case of failures is reversed to some agreed consistent state.
The goal, in the event of a failure, is normally to appear as if the work had never occurred in the first place.
With XTS, transactions can span multiple Web Services, meaning that work performed across multiple enterprises can be managed with transactional support.

== Managing service-Based Processes

XTS allows you to create transactions that drive complex business processes, spanning multiple Web Services.
Current Web Services standards do not address the requirements for a high-level coordination of services.
This is because in today's Web Services applications, which use single request/response interactions, coordination is typically not a problem.
However, for applications that engage multiple services among multiple business partners, coordinating and controlling the resulting interactions is essential.
This becomes even more apparent when you realize that you generally have little in the way of formal guarantees when interacting with third-party Web Services.

XTS provides the infrastructure for coordinating services during a business process.
By organizing processes as transactions, business partners can collaborate on complex business interactions in a reliable manner, insuring the integrity of their data - usually represented by multiple changes to a database – but without the usual overheads and drawbacks of directly exposing traditional transaction-processing engines directly onto the web.
<<example_application>> demonstrates how an application may manage service-based processes as transactions:

[[example_application]]
.An Evening On the Town
The application in question allows a user to plan a social evening.
This application is responsible for reserving a table at a restaurant, and reserving tickets to a show.
Both activities are paid for using a credit card.
In this example, each service represents exposed Web Services provided by different service providers.
XTS is used to envelop the interactions between the theater and restaurant services into a single (potentially) long-running business transaction.
The business transaction must insure that seats are reserved both at the restaurant and the theater.
If one event fails the user has the ability to decline both events, thus returning both services back to their original state.
If both events are successful, the user's credit card is charged and both seats are booked.
As you may expect, the interaction between the services must be controlled in a reliable manner over a period of time.
In addition, management must span several third-party services that are remotely deployed.

Without the backing of a transaction, an undesirable outcome may occur.
For example, the user credit card may be charged, even if one or both of the bookings fail.

<<example_application>> describes the situations where XTS excels at supporting business processes across multiple enterprises.
This example is further refined throughout this guide, and appears as a standard demonstrator (including source code) with the XTS distribution.

== Servlets

The WS-Coordination, WS-Atomic Transaction, and WS-Business Activity protocols are based on one-way interactions of entities rather than traditional synchronous request/response RPC-style interactions.
One group of entities, called transaction participants, invoke operations on other entities, such as the transaction coordinator, in order to return responses to requests.
The programming model is based on peer-to-peer relationships, with the result that all services, whether they are participants, coordinators or clients, must have an _active component_ that allows them to receive unsolicited messages.

In XTS, the active component is achieved through deployment of JaxWS endpoints.
Each XTS endpoint that is reachable through SOAP/XML is published via JaxWS, without developer intevention.
The only requirement is that transactional client applications and transactional web services must reside within a domain capable of hosting JaxWS endpoints, such as an application server.
{appServer} can provide this functionality.

== SOAP

SOAP has emerged as the de facto message format for XML-based communication in the Web Services arena.
It is a lightweight protocol that allows the user to define the content of a message and to provide hints as to how recipients should process that message.

== Web Services Description Language (WDSL)

[term]_Web Services Description Language (WSDL)_ is an XML-based language used to define Web service interfaces.
An application that consumes a Web service parses the service's WSDL document to discover the location of the service, the operations that the service supports, the protocol bindings the service supports (SOAP, HTTP, etc), and how to access them.
For each operation, WSDL describes the format that the client must follow.
