/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc. and/or its affiliates,
 * and individual contributors as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2010,
 * @author JBoss, by Red Hat.
 */
package com.arjuna.ats.internal.jta.utils;

import com.arjuna.common.util.logging.Logi18n;

/**
 * i18n log messages for the jtax module.
 * This class is autogenerated. Don't mess with it.
 *
 * @author Jonathan Halliday (jonathan.halliday@redhat.com) 2010-06
 */
public class jtaxI18NLoggerImpl implements jtaxI18NLogger {

	private final Logi18n logi18n;

	jtaxI18NLoggerImpl(Logi18n logi18n) {
		this.logi18n = logi18n;
	}

	public void log_com_arjuna_ats_internal_jta_recovery_jts_orbspecific_commit(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.recovery.jts.orbspecific.commit", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_recovery_jts_orbspecific_rollback(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.recovery.jts.orbspecific.rollback", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_consterror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.consterror", new Object[] {arg0, arg1});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_coperror(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.coperror", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_createstate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.createstate");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_generror(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.generror", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_lastResource_disableWarning() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.lastResource.disableWarning");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_lastResource_disallow(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.lastResource.disallow", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_lastResource_multipleWarning(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.lastResource.multipleWarning", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_lastResource_startupWarning() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.lastResource.startupWarning");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_loadstateread(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.loadstateread", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_norecoveryxa(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.norecoveryxa", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_notprepared(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.notprepared", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_nulltransaction(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.nulltransaction", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_preparefailed(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.preparefailed", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_recfailed(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.recfailed", new Object[] {arg0, arg1});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_remconn() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.remconn");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_restoreerror1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.restoreerror1", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_restoreerror2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.restoreerror2", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_saveState() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.saveState");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_unexpected(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.unexpected", new Object[] {arg0, arg1});
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_updatestate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.updatestate");
		}
	}

	public void log_com_arjuna_ats_internal_jta_resources_jts_orbspecific_xaerror(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.resources.jts.orbspecific.xaerror", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_alreadyassociated() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.alreadyassociated");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_delistfailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.delistfailed", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_endsuspendfailed1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.endsuspendfailed1");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_endsuspendfailed2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.endsuspendfailed2");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_illegalstate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.illegalstate");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_inactivetx() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.inactivetx");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_invalidtx() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.invalidtx");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_invalidtx2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.invalidtx2");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_jca_busy() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.jca.busy");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_lastResourceOptimisationInterface() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.lastResourceOptimisationInterface");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_markedrollback() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.markedrollback");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_nosuchtx() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.nosuchtx");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_nottximple() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.nottximple");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_notx() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.notx");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_notxe() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.notxe");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_nox() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.nox");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_nullparam() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.nullparam");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_regerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.regerror", new Object[] {arg0, arg1});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_ressusp() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.ressusp");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_rmerror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.rmerror");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_rollbackerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.rollbackerror", new Object[] {arg0, arg1});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_setrollback() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.setrollback");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_starterror(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.starterror", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_subordinate_invalidstate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.subordinate.invalidstate");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_syncerror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.syncerror");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_syncproblem() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.syncproblem");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_syncrollbackexception() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.syncrollbackexception");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_systemexception() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.systemexception");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_threaderror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.threaderror");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_unknownres(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.unknownres", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_wrongstatetx() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.wrongstatetx");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_xaenderror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.xaenderror");
		}
	}

	public void log_com_arjuna_ats_internal_jta_transaction_jts_xaerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jta.transaction.jts.xaerror", new Object[] {arg0, arg1});
		}
	}

}
