/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc. and/or its affiliates,
 * and individual contributors as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2010,
 * @author JBoss, by Red Hat.
 */
package com.arjuna.ats.jts.logging;

import com.arjuna.common.util.logging.Logi18n;

/**
 * i18n log messages for the jts module.
 * This class is autogenerated. Don't mess with it.
 *
 * @author Jonathan Halliday (jonathan.halliday@redhat.com) 2010-06
 */
public class jtsI18NLoggerImpl implements jtsI18NLogger {

	private final Logi18n logi18n;

	jtsI18NLoggerImpl(Logi18n logi18n) {
		this.logi18n = logi18n;
	}

	public void log_com_arjuna_ats_internal_arjuna_recovery_ExpiredAssumedCompleteScanner_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredAssumedCompleteScanner_1", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_arjuna_recovery_ExpiredAssumedCompleteScanner_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredAssumedCompleteScanner_2", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_arjuna_recovery_ExpiredAssumedCompleteScanner_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredAssumedCompleteScanner_3", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_arjuna_recovery_ExpiredAssumedCompleteScanner_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredAssumedCompleteScanner_4", new Object[] {arg0});
		}
	}

	public void log_com_arjuna_ats_internal_arjuna_recovery_ExpiredAssumedCompleteScanner_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredAssumedCompleteScanner_5", new Object[] {arg0, arg1});
		}
	}

	public void log_ORBManager() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.ORBManager");
		}
	}

	public void log_context_coorref(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.context.coorref", new Object[] {arg0, arg1});
		}
	}

	public void log_context_genfail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.context.genfail", new Object[] {arg0, arg1});
		}
	}

	public void log_context_orbnotsupported(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.context.orbnotsupported", new Object[] {arg0, arg1});
		}
	}

	public void log_context_picreffail() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.context.picreffail");
		}
	}

	public void log_cwabort() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.cwabort");
		}
	}

	public void log_cwcommit() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.cwcommit");
		}
	}

	public void log_interposition_cwabort() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.cwabort");
		}
	}

	public void log_interposition_fldefault(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.fldefault", new Object[] {arg0});
		}
	}

	public void log_interposition_resources_arjuna_ipfail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.ipfail", new Object[] {arg0, arg1});
		}
	}

	public void log_interposition_resources_arjuna_ipnt() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.ipnt");
		}
	}

	public void log_interposition_resources_arjuna_ipnull() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.ipnull");
		}
	}

	public void log_interposition_resources_arjuna_iptl(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.iptl", new Object[] {arg0, arg1});
		}
	}

	public void log_interposition_resources_arjuna_nochild(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.nochild", new Object[] {arg0});
		}
	}

	public void log_interposition_resources_arjuna_notchild(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.notchild", new Object[] {arg0});
		}
	}

	public void log_interposition_resources_arjuna_problemhierarchy(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.resources.arjuna.problemhierarchy", new Object[] {arg0});
		}
	}

	public void log_interposition_sfcaught(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.sfcaught", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_interposition_sfnoparent(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.interposition.sfnoparent", new Object[] {arg0});
		}
	}

	public void log_orbspecific_coordinator_generror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.generror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_coordinator_rbofail(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.rbofail", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_orbspecific_coordinator_rccreate(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.rccreate", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_coordinator_rcnotcreated() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.rcnotcreated");
		}
	}

	public void log_orbspecific_coordinator_txrun(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.txrun", new Object[] {arg0});
		}
	}

	public void log_orbspecific_coordinator_uidfail(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.uidfail", new Object[] {arg0});
		}
	}

	public void log_orbspecific_coordinator_zsync(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.coordinator.zsync", new Object[] {arg0});
		}
	}

	public void log_orbspecific_destroyfailed() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.destroyfailed");
		}
	}

	public void log_orbspecific_interposition_coordinator_generror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.coordinator.generror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_coordinator_syncerror(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.coordinator.syncerror", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_coordinator_txnotprepared(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.coordinator.txnotprepared", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_destfailed(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.destfailed", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_childerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.childerror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_generror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.generror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_generror_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.generror_2", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_ipfailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.ipfailed", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_ipfailed_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.ipfailed_2", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_nocoord(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.nocoord", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_notx(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.notx", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_nullcontrol_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.nullcontrol_1", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_nullcontrol_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.nullcontrol_2", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_arjuna_nullcoord(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.arjuna.nullcoord", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_destroyfailed() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.destroyfailed");
		}
	}

	public void log_orbspecific_interposition_resources_restricted_contx_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.restricted.contx_1");
		}
	}

	public void log_orbspecific_interposition_resources_restricted_contx_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.restricted.contx_4", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_restricted_contxfound_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.restricted.contxfound_1", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_restricted_contxfound_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.restricted.contxfound_3", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_interposition_resources_stateerror(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.stateerror", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_orbspecific_interposition_resources_strict_ipfailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.strict.ipfailed", new Object[] {arg0});
		}
	}

	public void log_orbspecific_interposition_resources_strict_iptlfailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.interposition.resources.strict.iptlfailed", new Object[] {arg0});
		}
	}

	public void log_orbspecific_invaliduid() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.invaliduid");
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_codeccreate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.codeccreate");
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_codecerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.codecerror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_duplicatename(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.duplicatename", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_error() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.error");
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_invalidparam() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.invalidparam");
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_sie() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.sie");
		}
	}

	public void log_orbspecific_jacorb_interceptors_context_srie(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.context.srie", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_codeccreate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.codeccreate");
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_codecerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.codecerror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_duplicatename(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.duplicatename", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_invalidparam() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.invalidparam");
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_sie() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.sie");
		}
	}

	public void log_orbspecific_jacorb_interceptors_interposition_srie(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.interceptors.interposition.srie", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ClientForwardInterceptor_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ClientForwardInterceptor_1");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ClientForwardInterceptor_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ClientForwardInterceptor_2");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ClientForwardInterceptor_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ClientForwardInterceptor_3");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ClientForwardInterceptor_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ClientForwardInterceptor_4");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ClientInitializer_() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ClientInitializer_");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbDefaultServant_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbDefaultServant_1", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbDefaultServant_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbDefaultServant_2", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCDefaultServant_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCDefaultServant_3", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCManager_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCManager_1", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCManager_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCManager_2");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCManager_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCManager_3");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCManager_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCManager_4");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCManager_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCManager_5", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_1");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_2");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_3");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_4");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_5");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_6(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_6", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_6a(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_6a", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_7", new Object[] {arg0});
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRCServiceInit_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRCServiceInit_8");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_JacOrbRecoveryInit_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.JacOrbRecoveryInit_1");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ServerInitializer_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ServerInitializer_1");
		}
	}

	public void log_orbspecific_jacorb_recoverycoordinators_ServerRecoveryInterceptor_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.jacorb.recoverycoordinators.ServerRecoveryInterceptor_1");
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_codeccreate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.codeccreate");
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_codecerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.codecerror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_duplicatename(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.duplicatename", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_error() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.error");
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_invalidparam() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.invalidparam");
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_sie() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.sie");
		}
	}

	public void log_orbspecific_javaidl_interceptors_context_srie(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.context.srie", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_codeccreate() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.codeccreate");
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_codecerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.codecerror", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_duplicatename(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.duplicatename", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_invalidparam() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.invalidparam");
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_sie() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.sie");
		}
	}

	public void log_orbspecific_javaidl_interceptors_interposition_srie(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.javaidl.interceptors.interposition.srie", new Object[] {arg0, arg1});
		}
	}

	public void log_orbspecific_otiderror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.otiderror");
		}
	}

	public void log_orbspecific_tficaught(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.tficaught", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_orbspecific_tidyfail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.orbspecific.tidyfail", new Object[] {arg0, arg1});
		}
	}

	public void log_otsservererror(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.otsservererror", new Object[] {arg0});
		}
	}

	public void log_otsserverfailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.otsserverfailed", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredContactScanner_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.ExpiredContactScanner_1", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredContactScanner_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.ExpiredContactScanner_2", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredContactScanner_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.ExpiredContactScanner_3", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredContactScanner_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.ExpiredContactScanner_4", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredContactScanner_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.ExpiredContactScanner_5", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_RecoveryEnablement_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_1");
		}
	}

	public void log_recovery_RecoveryEnablement_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_2");
		}
	}

	public void log_recovery_RecoveryEnablement_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_3", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_RecoveryEnablement_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_4");
		}
	}

	public void log_recovery_RecoveryEnablement_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_5", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryEnablement_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryEnablement_6", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryInit_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryInit_1");
		}
	}

	public void log_recovery_RecoveryInit_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryInit_2");
		}
	}

	public void log_recovery_RecoveryInit_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryInit_3", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryInit_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryInit_4");
		}
	}

	public void log_recovery_RecoveryInit_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.RecoveryInit_5", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_FactoryContactItem_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_1", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_FactoryContactItem_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_2");
		}
	}

	public void log_recovery_contact_FactoryContactItem_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_3");
		}
	}

	public void log_recovery_contact_FactoryContactItem_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_4", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_FactoryContactItem_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_5");
		}
	}

	public void log_recovery_contact_FactoryContactItem_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_6");
		}
	}

	public void log_recovery_contact_FactoryContactItem_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.FactoryContactItem_7", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_RecoveryContactWriter_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.RecoveryContactWriter_1");
		}
	}

	public void log_recovery_contact_RecoveryContactWriter_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.RecoveryContactWriter_2", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_RecoveryContactWriter_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.RecoveryContactWriter_3");
		}
	}

	public void log_recovery_contact_StatusChecker_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_1", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_contact_StatusChecker_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_10");
		}
	}

	public void log_recovery_contact_StatusChecker_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_11");
		}
	}

	public void log_recovery_contact_StatusChecker_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_12");
		}
	}

	public void log_recovery_contact_StatusChecker_13(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_13", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_14(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_14", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_15(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_15", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_contact_StatusChecker_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_2", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_contact_StatusChecker_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_3", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_4(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_4", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_contact_StatusChecker_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_5", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_6", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_7", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_8", new Object[] {arg0});
		}
	}

	public void log_recovery_contact_StatusChecker_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.contact.StatusChecker_9");
		}
	}

	public void log_recovery_rcnull(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.rcnull", new Object[] {arg0});
		}
	}

	public void log_recovery_recoverycoordinators_GenericRecoveryCoordinator_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.GenericRecoveryCoordinator_1", new Object[] {arg0});
		}
	}

	public void log_recovery_recoverycoordinators_GenericRecoveryCoordinator_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.GenericRecoveryCoordinator_2");
		}
	}

	public void log_recovery_recoverycoordinators_GenericRecoveryCoordinator_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.GenericRecoveryCoordinator_4", new Object[] {arg0});
		}
	}

	public void log_recovery_recoverycoordinators_GenericRecoveryCreator_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.GenericRecoveryCreator_1");
		}
	}

	public void log_recovery_recoverycoordinators_RecoveryCoordinatorId_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.RecoveryCoordinatorId_1", new Object[] {arg0});
		}
	}

	public void log_recovery_recoverycoordinators_RecoveryCoordinatorId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.RecoveryCoordinatorId_2");
		}
	}

	public void log_recovery_recoverycoordinators_RecoveryCoordinatorId_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.RecoveryCoordinatorId_3", new Object[] {arg0});
		}
	}

	public void log_recovery_recoverycoordinators_ResourceCompletor_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoverycoordinators.ResourceCompletor_1", new Object[] {arg0});
		}
	}

	public void log_recovery_recoveryinit_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.recoveryinit_1");
		}
	}

	public void log_recovery_transactions_AssumedCompleteServerTransaction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.AssumedCompleteServerTransaction_1", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_AssumedCompleteTransaction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.AssumedCompleteTransaction_1", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_CachedRecoveredTransaction_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.CachedRecoveredTransaction_1");
		}
	}

	public void log_recovery_transactions_CachedRecoveredTransaction_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.CachedRecoveredTransaction_2", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_1", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_10", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_11(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_11", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_12");
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_13() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_13");
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_14(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_14", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_15() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_15");
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_16(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_16", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_17(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_17", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_2", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_4(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_4", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_5", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_6", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_7", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_8", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredServerTransaction_9(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredServerTransaction_9", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_1", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_2", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_3", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_5", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_6", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_7", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_RecoveredTransaction_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.RecoveredTransaction_8");
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_1");
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_3");
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_4");
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_5", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_6", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_7", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_8(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_8", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_transactions_ServerTransactionRecoveryModule_9(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.ServerTransactionRecoveryModule_9", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TopLevelTransactionRecoveryModule_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TopLevelTransactionRecoveryModule_1");
		}
	}

	public void log_recovery_transactions_TopLevelTransactionRecoveryModule_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TopLevelTransactionRecoveryModule_2");
		}
	}

	public void log_recovery_transactions_TopLevelTransactionRecoveryModule_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TopLevelTransactionRecoveryModule_3");
		}
	}

	public void log_recovery_transactions_TopLevelTransactionRecoveryModule_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TopLevelTransactionRecoveryModule_4");
		}
	}

	public void log_recovery_transactions_TransactionCacheItem_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCacheItem_1", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCacheItem_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCacheItem_2", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_1");
		}
	}

	public void log_recovery_transactions_TransactionCache_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_2");
		}
	}

	public void log_recovery_transactions_TransactionCache_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_3", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_4", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_5", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_6", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_7", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionCache_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionCache_8", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_1");
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_10", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_11");
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_12");
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_2");
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_3", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_4");
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_5", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_6", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_7", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_8", new Object[] {arg0});
		}
	}

	public void log_recovery_transactions_TransactionRecoveryModule_9(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.recovery.transactions.TransactionRecoveryModule_9", new Object[] {arg0, arg1});
		}
	}

	public void log_resources_errgenerr(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errgenerr", new Object[] {arg0, arg1});
		}
	}

	public void log_resources_errnoparent(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errnoparent", new Object[] {arg0});
		}
	}

	public void log_resources_errnores(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errnores", new Object[] {arg0});
		}
	}

	public void log_resources_errsavefail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errsavefail", new Object[] {arg0, arg1});
		}
	}

	public void log_resources_errsetvalue(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errsetvalue", new Object[] {arg0});
		}
	}

	public void log_resources_errtypefail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.errtypefail", new Object[] {arg0, arg1});
		}
	}

	public void log_resources_noparent(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.noparent", new Object[] {arg0});
		}
	}

	public void log_resources_rrcaught(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.rrcaught", new Object[] {arg0, arg1});
		}
	}

	public void log_resources_rrillegalvalue(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.rrillegalvalue", new Object[] {arg0});
		}
	}

	public void log_resources_rrinvalid(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.jts.resources.rrinvalid", new Object[] {arg0});
		}
	}

	public void log_eicaughtexception(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.eicaughtexception", new Object[] {arg0, arg1});
		}
	}

	public void log_excalledagain(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.excalledagain", new Object[] {arg0});
		}
	}

	public void log_extensions_abortfail(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.abortfail", new Object[] {arg0});
		}
	}

	public void log_extensions_abortfailnoexist(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.abortfailnoexist", new Object[] {arg0});
		}
	}

	public void log_extensions_atcannotabort(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atcannotabort", new Object[] {arg0, arg1});
		}
	}

	public void log_extensions_atcurrenttxnull(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atcurrenttxnull", new Object[] {arg0});
		}
	}

	public void log_extensions_atgenerror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atgenerror", new Object[] {arg0, arg1});
		}
	}

	public void log_extensions_atnovalidtx(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atnovalidtx", new Object[] {arg0});
		}
	}

	public void log_extensions_atoutofseq(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atoutofseq", new Object[] {arg0, arg1});
		}
	}

	public void log_extensions_atscope(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atscope", new Object[] {arg0, arg1});
		}
	}

	public void log_extensions_atunavailable(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atunavailable", new Object[] {arg0});
		}
	}

	public void log_extensions_atwillabort(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.atwillabort", new Object[] {arg0});
		}
	}

	public void log_extensions_namefail() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.namefail");
		}
	}

	public void log_extensions_threadasserror(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.threadasserror", new Object[] {arg0, arg1});
		}
	}

	public void log_extensions_tltnestedscope(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.extensions.tltnestedscope", new Object[] {arg0});
		}
	}

	public void log_exunregfail(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.exunregfail", new Object[] {arg0});
		}
	}

	public void log_thread_resumefailed(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.thread.resumefailed", new Object[] {arg0, arg1});
		}
	}

	public void log_thread_resumefailederror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.thread.resumefailederror");
		}
	}

	public void log_utils_ORBSetup_orbalreadyset() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.jts.utils.ORBSetup.orbalreadyset");
		}
	}

}
