/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc. and/or its affiliates,
 * and individual contributors as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2010,
 * @author JBoss, by Red Hat.
 */
package com.arjuna.ats.arjuna.logging;

import com.arjuna.common.util.logging.Logi18n;

/**
 * i18n log messages for the arjuna module.
 * This class is autogenerated. Don't mess with it.
 *
 * @author Jonathan Halliday (jonathan.halliday@redhat.com) 2010-06
 */
public class arjunaI18NLoggerImpl implements arjunaI18NLogger {

	private final Logi18n logi18n;

	arjunaI18NLoggerImpl(Logi18n logi18n) {
		this.logi18n = logi18n;
	}

	public void log_ActivationRecord_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.ActivationRecord_1");
		}
	}

	public void log_ActivationRecord_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.ActivationRecord_2", new Object[] {arg0, arg1});
		}
	}

	public void log_CadaverRecord_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.CadaverRecord_1", new Object[] {arg0, arg1});
		}
	}

	public void log_DisposeRecord_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.DisposeRecord_1");
		}
	}

	public void log_DisposeRecord_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.DisposeRecord_2");
		}
	}

	public void log_DisposeRecord_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.DisposeRecord_3");
		}
	}

	public void log_DisposeRecord_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.DisposeRecord_4", new Object[] {arg0});
		}
	}

	public void log_DisposeRecord_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.DisposeRecord_5", new Object[] {arg0});
		}
	}

	public void log_PersistenceRecord_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_1", new Object[] {arg0, arg1});
		}
	}

	public void log_PersistenceRecord_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_10");
		}
	}

	public void log_PersistenceRecord_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_11");
		}
	}

	public void log_PersistenceRecord_12(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_12", new Object[] {arg0});
		}
	}

	public void log_PersistenceRecord_13() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_13");
		}
	}

	public void log_PersistenceRecord_14() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_14");
		}
	}

	public void log_PersistenceRecord_15() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_15");
		}
	}

	public void log_PersistenceRecord_16() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_16");
		}
	}

	public void log_PersistenceRecord_17() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_17");
		}
	}

	public void log_PersistenceRecord_18() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_18");
		}
	}

	public void log_PersistenceRecord_19() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_19");
		}
	}

	public void log_PersistenceRecord_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_2", new Object[] {arg0});
		}
	}

	public void log_PersistenceRecord_20(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_20", new Object[] {arg0});
		}
	}

	public void log_PersistenceRecord_21() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_21");
		}
	}

	public void log_PersistenceRecord_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_3");
		}
	}

	public void log_PersistenceRecord_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_4", new Object[] {arg0});
		}
	}

	public void log_PersistenceRecord_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_5");
		}
	}

	public void log_PersistenceRecord_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_6");
		}
	}

	public void log_PersistenceRecord_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_7");
		}
	}

	public void log_PersistenceRecord_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_8");
		}
	}

	public void log_PersistenceRecord_9(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.PersistenceRecord_9", new Object[] {arg0});
		}
	}

	public void log_RecoveryRecord_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.RecoveryRecord_1");
		}
	}

	public void log_RecoveryRecord_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.RecoveryRecord_2");
		}
	}

	public void log_StateManager_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_1");
		}
	}

	public void log_StateManager_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_10");
		}
	}

	public void log_StateManager_11(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_11", new Object[] {arg0, arg1});
		}
	}

	public void log_StateManager_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_12");
		}
	}

	public void log_StateManager_13() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_13");
		}
	}

	public void log_StateManager_14() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_14");
		}
	}

	public void log_StateManager_15() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_15");
		}
	}

	public void log_StateManager_16() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_16");
		}
	}

	public void log_StateManager_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_2", new Object[] {arg0, arg1});
		}
	}

	public void log_StateManager_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_3");
		}
	}

	public void log_StateManager_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_4");
		}
	}

	public void log_StateManager_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_5", new Object[] {arg0});
		}
	}

	public void log_StateManager_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_6", new Object[] {arg0});
		}
	}

	public void log_StateManager_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_7", new Object[] {arg0});
		}
	}

	public void log_StateManager_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_8");
		}
	}

	public void log_StateManager_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.StateManager_9");
		}
	}

	public void log_common_Mutex_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Mutex_1");
		}
	}

	public void log_common_Mutex_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Mutex_2");
		}
	}

	public void log_common_Uid_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_1");
		}
	}

	public void log_common_Uid_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_10");
		}
	}

	public void log_common_Uid_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_11");
		}
	}

	public void log_common_Uid_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_2");
		}
	}

	public void log_common_Uid_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_3", new Object[] {arg0});
		}
	}

	public void log_common_Uid_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_4", new Object[] {arg0});
		}
	}

	public void log_common_Uid_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_5", new Object[] {arg0});
		}
	}

	public void log_common_Uid_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_6");
		}
	}

	public void log_common_Uid_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_7");
		}
	}

	public void log_common_Uid_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_8");
		}
	}

	public void log_common_Uid_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_9");
		}
	}

	public void log_common_Uid_bytes() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_bytes");
		}
	}

	public void log_common_Uid_getbytes() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_getbytes");
		}
	}

	public void log_common_Uid_npe(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.common.Uid_npe", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_AbstractRecord_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.AbstractRecord_1");
		}
	}

	public void log_coordinator_AbstractRecord_npe(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.AbstractRecord_npe", new Object[] {arg0});
		}
	}

	public void log_coordinator_ActionHierarchy_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.ActionHierarchy_1");
		}
	}

	public void log_coordinator_BasicAction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_1", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_10(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_10", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_11(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_11", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_12(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_12", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_13(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_13", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_14(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_14", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_15(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_15", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_16() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_16");
		}
	}

	public void log_coordinator_BasicAction_17(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_17", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_18() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_18");
		}
	}

	public void log_coordinator_BasicAction_19(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_19", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_2", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_20(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_20", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_21(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_21", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_22(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_22", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_23(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_23", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_24() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_24");
		}
	}

	public void log_coordinator_BasicAction_25(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_25", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_26(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_26", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_27(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_27", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_28(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_28", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_29(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_29", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_3", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_30(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_30", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_31(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_31", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_32() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_32");
		}
	}

	public void log_coordinator_BasicAction_33(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_33", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_34(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_34", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_35(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_35", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_36(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_36", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_37(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_37", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_38() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_38");
		}
	}

	public void log_coordinator_BasicAction_39(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_39", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_40(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_40", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_41(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_41", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_42(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_42", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_43(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_43", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_44() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_44");
		}
	}

	public void log_coordinator_BasicAction_45(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_45", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_46(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_46", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_47(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_47", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_48() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_48");
		}
	}

	public void log_coordinator_BasicAction_49(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_49", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_5", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_50(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_50", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_51(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_51", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_52(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_52", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_53(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_53", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_54(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_54", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_55(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_55", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_56(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_56", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_57(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_57", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_58(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_58", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_59(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_59", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_5a(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_5a", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_6(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_6", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_60(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_60", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_61(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_61", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_62(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_62", new Object[] {arg0});
		}
	}

	public void log_coordinator_BasicAction_63(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_63", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_64() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_64");
		}
	}

	public void log_coordinator_BasicAction_65() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_65");
		}
	}

	public void log_coordinator_BasicAction_66(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_66", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_67(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_67", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_68() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_68");
		}
	}

	public void log_coordinator_BasicAction_69() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_69");
		}
	}

	public void log_coordinator_BasicAction_7(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_7", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_BasicAction_70() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_70");
		}
	}

	public void log_coordinator_BasicAction_71(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_71", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_8(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_8", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_BasicAction_9(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.BasicAction_9", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_CheckedAction_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.CheckedAction_1", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_CheckedAction_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.CheckedAction_2", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_RecordList_1(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_1", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_coordinator_RecordList_2(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_2", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_coordinator_RecordList_3(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_3", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_coordinator_RecordList_4(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_4", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_coordinator_RecordList_5(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_5", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_RecordList_6(String arg0, String arg1, String arg2, String arg3, String arg4) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.RecordList_6", new Object[] {arg0, arg1, arg2, arg3, arg4});
		}
	}

	public void log_coordinator_TransactionReaper_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_1");
		}
	}

	public void log_coordinator_TransactionReaper_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_10", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_11(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_11", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_12(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_12", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_13(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_13", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_coordinator_TransactionReaper_14(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_14", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_15(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_15", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_16(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_16", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_17(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_17", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_18(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_18", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_19() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_19");
		}
	}

	public void log_coordinator_TransactionReaper_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_2", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_3", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_4", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_5", new Object[] {arg0});
		}
	}

	public void log_coordinator_TransactionReaper_6(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_6", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_7(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_7", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_8(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_8", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TransactionReaper_9(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TransactionReaper_9", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_1");
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_2", new Object[] {arg0});
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_3");
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_4", new Object[] {arg0});
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_4a(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_4a", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TwoPhaseCoordinator_4b(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator_4b", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_TxControl_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TxControl_1", new Object[] {arg0});
		}
	}

	public void log_coordinator_TxControl_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TxControl_2", new Object[] {arg0});
		}
	}

	public void log_coordinator_TxControl_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.TxControl_3", new Object[] {arg0});
		}
	}

	public void log_coordinator_cafactoryerror() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.cafactoryerror");
		}
	}

	public void log_coordinator_checkedactionfactory(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.checkedactionfactory", new Object[] {arg0});
		}
	}

	public void log_coordinator_invalidos() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.invalidos");
		}
	}

	public void log_coordinator_norecordfound(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.norecordfound", new Object[] {arg0});
		}
	}

	public void log_coordinator_notrunning() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.notrunning");
		}
	}

	public void log_coordinator_toolong() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.coordinator.toolong");
		}
	}

	public void log_lastResource_disableWarning() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.lastResource.disableWarning");
		}
	}

	public void log_lastResource_disallow(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.lastResource.disallow", new Object[] {arg0});
		}
	}

	public void log_lastResource_multipleWarning(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.lastResource.multipleWarning", new Object[] {arg0});
		}
	}

	public void log_lastResource_startupWarning() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.lastResource.startupWarning");
		}
	}

	public void log_objectstore_ObjectStoreType_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.objectstore.ObjectStoreType_1", new Object[] {arg0});
		}
	}

	public void log_objectstore_ObjectStoreType_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.objectstore.ObjectStoreType_2");
		}
	}

	public void log_objectstore_ObjectStore_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.objectstore.ObjectStore_1");
		}
	}

	public void log_recovery_ActionStatucService_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatucService_5", new Object[] {arg0});
		}
	}

	public void log_recovery_ActionStatusService_1(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_1", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_recovery_ActionStatusService_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_2", new Object[] {arg0});
		}
	}

	public void log_recovery_ActionStatusService_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_3");
		}
	}

	public void log_recovery_ActionStatusService_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_4", new Object[] {arg0});
		}
	}

	public void log_recovery_ActionStatusService_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_6", new Object[] {arg0});
		}
	}

	public void log_recovery_ActionStatusService_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.ActionStatusService_7");
		}
	}

	public void log_recovery_RecoverAtomicAction_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoverAtomicAction_1", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_RecoverAtomicAction_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoverAtomicAction_2", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoverAtomicAction_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoverAtomicAction_3", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoverAtomicAction_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoverAtomicAction_4", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoverAtomicAction_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoverAtomicAction_5", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryManager_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoveryManager_1", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryManager_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoveryManager_2", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryManager_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoveryManager_3", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_RecoveryManager_4(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoveryManager_4", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_RecoveryManager_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.RecoveryManager_5");
		}
	}

	public void log_recovery_TransactionStatusConnectionManager_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusConnectionManager_1", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusConnectionManager_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusConnectionManager_2", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusConnectionManager_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusConnectionManager_3", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusConnectionManager_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusConnectionManager_4", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_1", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_TransactionStatusManager_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_10", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_11");
		}
	}

	public void log_recovery_TransactionStatusManager_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_12");
		}
	}

	public void log_recovery_TransactionStatusManager_13() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_13");
		}
	}

	public void log_recovery_TransactionStatusManager_14(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_14", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_TransactionStatusManager_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_2");
		}
	}

	public void log_recovery_TransactionStatusManager_3(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_3", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_recovery_TransactionStatusManager_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_4", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_5", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_6", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_7", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_8", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManager_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.recovery.TransactionStatusManager_9");
		}
	}

	public void log_state_InputBuffer_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_1");
		}
	}

	public void log_state_InputBuffer_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_10");
		}
	}

	public void log_state_InputBuffer_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_11");
		}
	}

	public void log_state_InputBuffer_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_2");
		}
	}

	public void log_state_InputBuffer_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_3");
		}
	}

	public void log_state_InputBuffer_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_4");
		}
	}

	public void log_state_InputBuffer_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_5");
		}
	}

	public void log_state_InputBuffer_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_6");
		}
	}

	public void log_state_InputBuffer_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_7");
		}
	}

	public void log_state_InputBuffer_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_8");
		}
	}

	public void log_state_InputBuffer_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.InputBuffer_9");
		}
	}

	public void log_state_OutputBuffer_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_1");
		}
	}

	public void log_state_OutputBuffer_10() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_10");
		}
	}

	public void log_state_OutputBuffer_11() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_11");
		}
	}

	public void log_state_OutputBuffer_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_2");
		}
	}

	public void log_state_OutputBuffer_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_3");
		}
	}

	public void log_state_OutputBuffer_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_4");
		}
	}

	public void log_state_OutputBuffer_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_5");
		}
	}

	public void log_state_OutputBuffer_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_6");
		}
	}

	public void log_state_OutputBuffer_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_7");
		}
	}

	public void log_state_OutputBuffer_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_8");
		}
	}

	public void log_state_OutputBuffer_9() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.state.OutputBuffer_9");
		}
	}

	public void log_tools_osb_mbean_m_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.mbean.m_1");
		}
	}

	public void log_tools_osb_mbean_m_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.mbean.m_2");
		}
	}

	public void log_tools_osb_mbean_m_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.mbean.m_3", new Object[] {arg0});
		}
	}

	public void log_tools_osb_util_JMXServer_m_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_1", new Object[] {arg0});
		}
	}

	public void log_tools_osb_util_JMXServer_m_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_2", new Object[] {arg0});
		}
	}

	public void log_tools_osb_util_JMXServer_m_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_3", new Object[] {arg0, arg1});
		}
	}

	public void log_tools_osb_util_JMXServer_m_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_4", new Object[] {arg0});
		}
	}

	public void log_tools_osb_util_JMXServer_m_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_5]", new Object[] {arg0, arg1});
		}
	}

	public void log_tools_osb_util_JMXServer_m_6(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.tools.osb.util.JMXServer.m_6", new Object[] {arg0, arg1});
		}
	}

	public void log_utils_FileLock_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_1", new Object[] {arg0});
		}
	}

	public void log_utils_FileLock_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_2", new Object[] {arg0});
		}
	}

	public void log_utils_FileLock_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_3", new Object[] {arg0});
		}
	}

	public void log_utils_FileLock_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_4", new Object[] {arg0});
		}
	}

	public void log_utils_FileLock_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_5", new Object[] {arg0});
		}
	}

	public void log_utils_FileLock_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.FileLock_6", new Object[] {arg0});
		}
	}

	public void log_utils_Utility_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.Utility_1");
		}
	}

	public void log_utils_Utility_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.arjuna.utils.Utility_2");
		}
	}

	public void log_ats_atomicaction_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.atomicaction_1", new Object[] {arg0});
		}
	}

	public void log_abstractrecords_smf1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.abstractrecords.smf1");
		}
	}

	public void log_abstractrecords_smf2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.abstractrecords.smf2");
		}
	}

	public void log_abstractrecords_smf3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.abstractrecords.smf3");
		}
	}

	public void log_common_ClassloadingUtility_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_1");
		}
	}

	public void log_common_ClassloadingUtility_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_2", new Object[] {arg0});
		}
	}

	public void log_common_ClassloadingUtility_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_3", new Object[] {arg0, arg1});
		}
	}

	public void log_common_ClassloadingUtility_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_4", new Object[] {arg0});
		}
	}

	public void log_common_ClassloadingUtility_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_5", new Object[] {arg0});
		}
	}

	public void log_common_ClassloadingUtility_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.common.ClassloadingUtility_6", new Object[] {arg0});
		}
	}

	public void log_coordinator_ReaperThread_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.coordinator.ReaperThread_1", new Object[] {arg0, arg1});
		}
	}

	public void log_coordinator_ReaperWorkerThread_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread_1", new Object[] {arg0});
		}
	}

	public void log_coordinator_ReaperWorkerThread_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread_2", new Object[] {arg0});
		}
	}

	public void log_objectstore_ActionStore_1(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ActionStore_1", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_objectstore_CacheStore_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.CacheStore_1", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_CacheStore_2(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.CacheStore_2", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_objectstore_CacheStore_3(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.CacheStore_3", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_objectstore_CacheStore_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.CacheStore_4", new Object[] {arg0});
		}
	}

	public void log_objectstore_FileSystemStore_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_1", new Object[] {arg0});
		}
	}

	public void log_objectstore_FileSystemStore_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_2", new Object[] {arg0});
		}
	}

	public void log_objectstore_FileSystemStore_20(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_20", new Object[] {arg0});
		}
	}

	public void log_objectstore_FileSystemStore_2a() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_2a");
		}
	}

	public void log_objectstore_FileSystemStore_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_3");
		}
	}

	public void log_objectstore_FileSystemStore_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_4");
		}
	}

	public void log_objectstore_FileSystemStore_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_5");
		}
	}

	public void log_objectstore_FileSystemStore_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_6");
		}
	}

	public void log_objectstore_FileSystemStore_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_7");
		}
	}

	public void log_objectstore_FileSystemStore_8() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.FileSystemStore_8");
		}
	}

	public void log_objectstore_HashedStore_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.HashedStore_1", new Object[] {arg0});
		}
	}

	public void log_objectstore_HashedStore_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.HashedStore_2", new Object[] {arg0});
		}
	}

	public void log_objectstore_HashedStore_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.HashedStore_5");
		}
	}

	public void log_objectstore_HashedStore_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.HashedStore_6");
		}
	}

	public void log_objectstore_JDBCImple_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_1", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_10", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_11(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_11", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_12(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_12", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_13(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_13", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_14(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_14", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_15(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_15", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_16(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_16", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_17() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_17");
		}
	}

	public void log_objectstore_JDBCImple_18() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_18");
		}
	}

	public void log_objectstore_JDBCImple_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_2", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_3", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_4", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_5", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_6", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_7(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_7", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_8", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCImple_9(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_9", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_JDBCImple_readfailed() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_readfailed");
		}
	}

	public void log_objectstore_JDBCImple_writefailed(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCImple_writefailed", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCStore_1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCStore_1", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_JDBCStore_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCStore_2", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_JDBCStore_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCStore_3");
		}
	}

	public void log_objectstore_JDBCStore_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCStore_4", new Object[] {arg0});
		}
	}

	public void log_objectstore_JDBCStore_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.JDBCStore_5");
		}
	}

	public void log_objectstore_ShadowingStore_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_1");
		}
	}

	public void log_objectstore_ShadowingStore_10(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_10", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_11(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_11", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_12(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_12", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_13() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_13");
		}
	}

	public void log_objectstore_ShadowingStore_14(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_14", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_15(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_15", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_16(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_16", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_17(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_17", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_18(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_18", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_19(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_19", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_2", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_20(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_20", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_21(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_21", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_22(String arg0, String arg1, String arg2) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_22", new Object[] {arg0, arg1, arg2});
		}
	}

	public void log_objectstore_ShadowingStore_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_3", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_4(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_4", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_ShadowingStore_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_5", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_6");
		}
	}

	public void log_objectstore_ShadowingStore_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_7");
		}
	}

	public void log_objectstore_ShadowingStore_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_8", new Object[] {arg0});
		}
	}

	public void log_objectstore_ShadowingStore_9(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.ShadowingStore_9", new Object[] {arg0, arg1});
		}
	}

	public void log_objectstore_jdbc_oracle_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.jdbc.oracle_1");
		}
	}

	public void log_objectstore_jdbc_oracle_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.jdbc.oracle_2", new Object[] {arg0});
		}
	}

	public void log_objectstore_notypenameuid() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.notypenameuid");
		}
	}

	public void log_objectstore_packProblem() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.objectstore.packProblem");
		}
	}

	public void log_recovery_AtomicActionRecoveryModule_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule_1", new Object[] {arg0});
		}
	}

	public void log_recovery_AtomicActionRecoveryModule_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule_2", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_AtomicActionRecoveryModule_3(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule_3", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_AtomicActionRecoveryModule_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule_4");
		}
	}

	public void log_recovery_AtomicActionRecoveryModule_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule_5");
		}
	}

	public void log_recovery_Connection_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.Connection_1");
		}
	}

	public void log_recovery_Connection_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.Connection_2");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_1", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_10", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_11(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_11", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_12(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_12", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_2");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_3");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_4");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_5() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_5");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_6(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_6", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_7() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_7");
		}
	}

	public void log_recovery_ExpiredEntryMonitor_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_8", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredEntryMonitor_9(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredEntryMonitor_9", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionScanner_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionScanner_1", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionScanner_2(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionScanner_2", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_ExpiredTransactionScanner_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionScanner_3", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionScanner_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionScanner_4", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionStatusManagerScanner_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner_1", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionStatusManagerScanner_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner_2", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionStatusManagerScanner_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner_3", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionStatusManagerScanner_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner_4", new Object[] {arg0});
		}
	}

	public void log_recovery_ExpiredTransactionStatusManagerScanner_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.ExpiredTransactionStatusManagerScanner_5", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_Listener_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.Listener_2");
		}
	}

	public void log_recovery_PeriodicRecovery_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_1");
		}
	}

	public void log_recovery_PeriodicRecovery_10(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_10", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_11(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_11", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_12() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_12");
		}
	}

	public void log_recovery_PeriodicRecovery_13(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_13", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_PeriodicRecovery_14(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_14", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_15(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_15", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_2", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_3", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_4", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_5", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_6(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_6", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_PeriodicRecovery_7(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_7", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_PeriodicRecovery_8(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_8", new Object[] {arg0});
		}
	}

	public void log_recovery_PeriodicRecovery_9(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery_9", new Object[] {arg0});
		}
	}

	public void log_recovery_RecActivatorLoader_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_1");
		}
	}

	public void log_recovery_RecActivatorLoader_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_2", new Object[] {arg0});
		}
	}

	public void log_recovery_RecActivatorLoader_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_3", new Object[] {arg0});
		}
	}

	public void log_recovery_RecActivatorLoader_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_4", new Object[] {arg0});
		}
	}

	public void log_recovery_RecActivatorLoader_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_5", new Object[] {arg0});
		}
	}

	public void log_recovery_RecActivatorLoader_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecActivatorLoader_6");
		}
	}

	public void log_recovery_RecoveryManagerImple_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecoveryManagerImple_1", new Object[] {arg0});
		}
	}

	public void log_recovery_RecoveryManagerImple_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.RecoveryManagerImple_2", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusConnector_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_1");
		}
	}

	public void log_recovery_TransactionStatusConnector_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_2");
		}
	}

	public void log_recovery_TransactionStatusConnector_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_3");
		}
	}

	public void log_recovery_TransactionStatusConnector_4(String arg0, String arg1, String arg2, String arg3) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_4", new Object[] {arg0, arg1, arg2, arg3});
		}
	}

	public void log_recovery_TransactionStatusConnector_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_5", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusConnector_6() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusConnector_6");
		}
	}

	public void log_recovery_TransactionStatusManagerItem_1(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusManagerItem_1", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManagerItem_2(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusManagerItem_2", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManagerItem_3(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusManagerItem_3", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManagerItem_4(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusManagerItem_4", new Object[] {arg0});
		}
	}

	public void log_recovery_TransactionStatusManagerItem_5(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.TransactionStatusManagerItem_5", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_WorkerService_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.WorkerService_1");
		}
	}

	public void log_recovery_WorkerService_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.WorkerService_2");
		}
	}

	public void log_recovery_WorkerService_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.WorkerService_3");
		}
	}

	public void log_recovery_WorkerService_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.WorkerService_4");
		}
	}

	public void log_recovery_fail(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.fail", new Object[] {arg0, arg1});
		}
	}

	public void log_recovery_localready() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.localready");
		}
	}

	public void log_recovery_socketready(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.recovery.socketready", new Object[] {arg0});
		}
	}

	public void log_tools_log_eaa1(String arg0, String arg1) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.tools.log.eaa1", new Object[] {arg0, arg1});
		}
	}

	public void log_tools_log_eaa2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.tools.log.eaa2");
		}
	}

	public void log_utils_ExecProcessId_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ExecProcessId_1");
		}
	}

	public void log_utils_ExecProcessId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ExecProcessId_2");
		}
	}

	public void log_utils_ExecProcessId_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ExecProcessId_3");
		}
	}

	public void log_utils_ExecProcessId_4() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ExecProcessId_4");
		}
	}

	public void log_utils_ExecProcessId_5(String arg0) {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ExecProcessId_5", new Object[] {arg0});
		}
	}

	public void log_utils_FileProcessId_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.FileProcessId_1");
		}
	}

	public void log_utils_FileProcessId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.FileProcessId_2");
		}
	}

	public void log_utils_MBeanProcessId_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.MBeanProcessId_1");
		}
	}

	public void log_utils_MBeanProcessId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.MBeanProcessId_2");
		}
	}

	public void log_utils_ManualProcessId_1() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ManualProcessId_1");
		}
	}

	public void log_utils_ManualProcessId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ManualProcessId_2");
		}
	}

	public void log_utils_ManualProcessId_3() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.ManualProcessId_3");
		}
	}

	public void log_utils_SocketProcessId_2() {
		if(logi18n.isWarnEnabled()) {
			logi18n.warn("com.arjuna.ats.internal.arjuna.utils.SocketProcessId_2");
		}
	}
}
