/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat Inc., and individual contributors as indicated
 * by the @authors tag.  All rights reserved.
 * See the copyright.txt in the distribution for a full listing
 * of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2005-2006,
 * @author JBoss Inc.
 */
package com.arjuna.webservices11.soapfault;

import javax.xml.namespace.QName;

/**
 * constants identifying the soap fault service employed for JaxWS dispatch and delivery of asynch fauls generated by
 * endpoint web methods which implement oneway messages
 */
public interface SoapFaultConstants
{
    /**
     * The Namespace.
     */
    public String SOAPFAULT_NAMESPACE = "http://jbossts.jboss.org/xts/soapfault" ;

    /**
     * the service name
     */
    public String SOAPFAULT_SERVICE_NAME = "SoapFaultService";

    /**
     * the service QName
     */
    public QName SOAPFAULT_SERVICE_QNAME = new QName(SOAPFAULT_NAMESPACE, SOAPFAULT_SERVICE_NAME);

    /**
     * the port name
     */
    public String SOAPFAULT_PORT_NAME = "SoapFaultPortType";

    /**
     * the port QName
     */
    public QName SOAPFAULT_PORT_QNAME = new QName(SOAPFAULT_NAMESPACE, SOAPFAULT_PORT_NAME);
}
