/*
 * SPDX short identifier: Apache-2.0
 */



#ifndef COSTSPORTABILITY_IDL_
#define COSTSPORTABILITY_IDL_

#pragma prefix "omg.org"

#include <idl/CosTransactions.idl>

module CosTSPostability  // PIDL
{
    typedef long ReqId;

    interface Sender
    {
	void sending_request (in ReqId id, out CosTransactions::PropagationContext ctx);
	void received_reply (in ReqId id, in CosTransactions::PropagationContext ctx,
			     in CORBA::Environment env);
    };

    interface Receiver
    {
	void received_request (in ReqId id, in CosTransactions::PropagationContext ctx);
	void sending_reply (in ReqId id, out CosTransactions::PropagationContext ctx);
    };
	
};

#endif