/*
 * SPDX short identifier: Apache-2.0
 */


#ifndef COSTSINTEROPERATION_IDL_
#define COSTSINTEROPERATION_IDL_

// The TAG_TRANSACTION_POLICY component is deprecated and // 
// replaced by InvocationPolicy and OTSPolicy components //
// It is retained for backward compatibility only. //

module CosTSInteroperation 
{
	const IOP::ComponentId TAG_TRANSACTION_POLICY=26:
	struct TransactionPolicyComponent { CosTransactions::TransactionPolicyValue tpv; };

	const IOP::ComponentId TAG_OTS_POLICY= 31;
	const IOP::ComponentId TAG_INV_POLICY= 32;
};

#endif