/*
 * SPDX short identifier: Apache-2.0
 */



#ifndef TSIDENTIFICATION_IDL_
#define TSIDENTIFICATION_IDL_

#pragma prefix "omg.org"

#include <idl/CosTSPortability.idl>

interface TSIdentification  // PIDL
{
    exception NotAvailable {};
    exception AlreadyIdentified {};

    void identify_sender (in CosTSPortability::Sender sender) raises (NotAvailable, AlreadyIdentified);
    void identify_receiver (in CosTSPortability::Receiver receiver) raises (NotAvailable, AlreadyIdentified);
};