/*
 * SPDX short identifier: Apache-2.0
 */

#ifndef NO_PRAGMA_SUPPORT
#pragma prefix "orbspecific.orbportability.mwtests.hp.com"
#endif

// used by the orbportability module tests
module orbtests
{
	interface SimpleObject
	{
		string test();
	};
};