/*
 * SPDX short identifier: Apache-2.0
 */

#include <CosTransactions.idl>

// used by the jtax module tests
module Example
{
    interface test : CosTransactions::TransactionalObject
    {
	    void invoke ();
	};
};