<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wscoor="http://docs.oasis-open.org/ws-tx/wscoor/2006/06" targetNamespace="http://docs.oasis-open.org/ws-tx/wscoor/2006/06" xmlns:wsaw="http://www.w3.org/2006/02/addressing/wsdl">

  <wsdl:import
      namespace="http://docs.oasis-open.org/ws-tx/wscoor/2006/06"
      location="wscoor.wsdl" />

  <wsdl:binding name="Activation_SOAPBinding" type="wscoor:ActivationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CreateCoordinationContextOperation">
            <soap:operation soapAction="http://docs.oasis-open.org/ws-tx/wscoor/2006/06/CreateCoordinationContext"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ActivationService">
     <wsdl:port binding="wscoor:Activation_SOAPBinding" name="ActivationPortType">
       <wsaw:UsingAddressing required="true"/>
      <soap:address location="http://localhost:9000/ws-c11/ActivationService"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
