/*
 * SPDX short identifier: Apache-2.0
 */


//

#include <CosTransactions.idl>

#pragma prefix "qa.jbossts.jboss.org"

module AITResources01
{
    exception InvocationException {};

    interface Counter : CosTransactions::TransactionalObject
    {
        void get(out long value)
            raises (InvocationException);
        void set(in long value)
            raises (InvocationException);
        void increase()
            raises (InvocationException);

        long getMemory();
    };

    interface PingPong : CosTransactions::TransactionalObject
    {
        void hit(in long count, in PingPong ponger, in PingPong pinger)
            raises (InvocationException);
        void bad_hit(in long count, in long bad_count, in PingPong ponger, in PingPong pinger)
            raises (InvocationException);
        void get(out long value)
            raises (InvocationException);

        long getMemory();
    };
};