/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module AITResources02
{
    exception InvocationException {};

    interface Counter
    {
        void get(out long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void set(in long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void increase(in CosTransactions::Control ctrl)
            raises (InvocationException);

        long getMemory();
    };

    interface PingPong
    {
        void hit(in long count, in PingPong ponger, in PingPong pinger, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void bad_hit(in long count, in long bad_count, in PingPong ponger, in PingPong pinger, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void get(out long value, in CosTransactions::Control ctrl)
            raises (InvocationException);

        long getMemory();
    };
};