/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery06
{
    interface Service
    {
        void    setup_oper(in CosTransactions::Control ctrl);
        boolean check_oper();
        boolean is_correct();
    };
};