/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery09
{
    exception InvocationException {};

    interface Service : CosTransactions::TransactionalObject
    {
        void set(in  long value)
            raises (InvocationException);
        void get(out long value)
            raises (InvocationException);
    };
};