/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery10
{
    exception InvocationException {};

    interface Service
    {
        void set(in CosTransactions::Control ctrl, in  long value)
            raises (InvocationException);
        void get(in CosTransactions::Control ctrl, out long value)
            raises (InvocationException);
    };
};