/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery11
{
    enum CrashBehavior
    {
        CrashBehaviorCrashInPrepare,
        CrashBehaviorCrashInCommit,
        CrashBehaviorCrashInRollback,
        CrashBehaviorCrashInCommitOnePhase,
        CrashBehaviorCrashInForget,
        CrashBehaviorNoCrash
    };

    struct ResourceBehavior
    {
        CrashBehavior crash_behavior;
    };

    exception InvocationException {};

    interface BeforeCrashService : CosTransactions::TransactionalObject
    {
        void set(in  long value)
            raises (InvocationException);

        void get(out long value)
            raises (InvocationException);

        void setStartCrashAbstractRecordAction(in CrashBehavior action)
            raises (InvocationException);

        void setEndCrashAbstractRecordAction(in CrashBehavior action)
            raises (InvocationException);

        boolean is_correct();

    };

    interface AfterCrashService
    {
        void get(out long value)
            raises (InvocationException);
    };

};