/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery03
{
    interface Service : CosTransactions::TransactionalObject
    {
        void    setup_oper();
        boolean check_oper();
        boolean is_correct();
    };
};