/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module CrashRecovery01
{
    enum ResourceTrace
    {
        ResourceTraceUnknown,
        ResourceTraceNone,
        ResourceTracePrepare,
        ResourceTracePrepareCommit,
        ResourceTracePrepareRollback,
        ResourceTraceCommitOnePhase,
        ResourceTraceRollback
    };

    interface Service : CosTransactions::TransactionalObject
    {
        void    setup_oper(in long number_of_resources);
        boolean check_oper();

        boolean       is_correct();
        ResourceTrace get_resource_trace(in long resource_number);
    };
};