/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module EnlistDelistEnlist01
{
    exception InvocationException {};

    interface Service
    {
        void begin_begin()
            raises (InvocationException);

        void begin_enlist_delist_enlist_commit()
            raises (InvocationException);

        void begin_enlist_delist_close_commit()
            raises (InvocationException);

        void begin_enlist_enlist_delist_commit()
            raises (InvocationException);

        boolean isCorrect()
            raises (InvocationException);


    };
};