/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module Hammer02
{
    enum Reason
    {
        ReasonUnknown,
        ReasonConcurrencyControl
    };

    exception InvocationException
    {
        Reason myreason;
    };

    interface Matrix
    {
        long get_width()
            raises (InvocationException);
        long get_height()
            raises (InvocationException);
        void get_value(in long x, in long y, out long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void set_value(in long x, in long y, in long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
    };
};