/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module Issues0001
{
    exception InvocationException {};

    interface Counter : CosTransactions::TransactionalObject
    {
        void get(out long value)
            raises (InvocationException);
        void set(in long value)
            raises (InvocationException);
        void increase()
            raises (InvocationException);
    };
};