/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module JDBCResources02
{
    exception InvocationException {};

    interface InfoTable
    {
        void insert(in string name, in string value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void update(in string name, in string value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void select(in string name, out string value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void delete(in string name, in CosTransactions::Control ctrl)
            raises (InvocationException);
    };
};