/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module JDBCResources03
{
	enum Reason {
		ReasonCantSerializeAccess,
		ReasonUnknown
	};

    exception InvocationException {
    	Reason	myreason;
    };

    interface NumberTable : CosTransactions::TransactionalObject
    {
        void get(in string name, out long value)
            raises (InvocationException);
        void set(in string name, in long value)
            raises (InvocationException);
        void increase(in string name)
            raises (InvocationException);
    };
};