/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module JDBCResources01
{
    exception InvocationException {};

    interface InfoTable : CosTransactions::TransactionalObject
    {
        void insert(in string name, in string value)
            raises (InvocationException);
        void update(in string name, in string value)
            raises (InvocationException);
        void select(in string name, out string value)
            raises (InvocationException);
        void delete(in string name)
            raises (InvocationException);
    };
};