/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module JDBCResources04
{
	enum Reason {
		ReasonCantSerializeAccess,
		ReasonUnknown
	};

    exception InvocationException {
    	Reason	myreason;
    };

    interface NumberTable
    {
        void get(in string name, out long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void set(in string name, in long value, in CosTransactions::Control ctrl)
            raises (InvocationException);
        void increase(in string name, in CosTransactions::Control ctrl)
            raises (InvocationException);
    };
};