/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module PerfProfile01
{
    exception InvocationException {};

    interface NullObject
    {
        void nulloper()
            raises (InvocationException);
    };

    interface ImplicitObject : CosTransactions::TransactionalObject
    {
        void no_tran_nulloper()
            raises (InvocationException);
        void no_tran_readlock()
            raises (InvocationException);
        void no_tran_writelock()
            raises (InvocationException);
        void tran_commit_nulloper()
            raises (InvocationException);
        void tran_commit_readlock()
            raises (InvocationException);
        void tran_commit_writelock()
            raises (InvocationException);
        void tran_rollback_nulloper()
            raises (InvocationException);
        void tran_rollback_readlock()
            raises (InvocationException);
        void tran_rollback_writelock()
            raises (InvocationException);
    };

    interface ExplicitObject
    {
        void no_tran_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void no_tran_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void no_tran_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
    };
};