/*
 * JBoss, Home of Professional Open Source
 * Copyright 2007, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2005-2006,
 * @author JBoss Inc.
 */
//
// Copyright (C) 2000,
//
// Arjuna Solutions, Ltd.,
// Newcastle upon Tyne,
// Tyne and Wear,
// UK.
//
// $Id: PerfProfile01.idl,v 1.3 2004/03/19 15:43:51 jcoleman Exp $
//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module PerfProfile01
{
    exception InvocationException {};

    interface NullObject
    {
        void nulloper()
            raises (InvocationException);
    };

    interface ImplicitObject : CosTransactions::TransactionalObject
    {
        void no_tran_nulloper()
            raises (InvocationException);
        void no_tran_readlock()
            raises (InvocationException);
        void no_tran_writelock()
            raises (InvocationException);
        void tran_commit_nulloper()
            raises (InvocationException);
        void tran_commit_readlock()
            raises (InvocationException);
        void tran_commit_writelock()
            raises (InvocationException);
        void tran_rollback_nulloper()
            raises (InvocationException);
        void tran_rollback_readlock()
            raises (InvocationException);
        void tran_rollback_writelock()
            raises (InvocationException);
    };

    interface ExplicitObject
    {
        void no_tran_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void no_tran_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void no_tran_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_commit_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_nulloper(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_readlock(in CosTransactions::Control ctrl)
            raises (InvocationException);
        void tran_rollback_writelock(in CosTransactions::Control ctrl)
            raises (InvocationException);
    };
};


