
#include <CosTransactions.idl>

#pragma prefix "qa.jbossts.jboss.org"

module performance
{
    exception PerfTestException { };

    interface PerfTestInterface : CosTransactions::TransactionalObject
    {
        void work() raises(PerfTestException);
    };
};

