/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module RawResources01
{
    enum PrepareBehavior
    {
        PrepareBehaviorReturnVoteCommit,
        PrepareBehaviorReturnVoteRollback,
        PrepareBehaviorReturnVoteReadOnly,
        PrepareBehaviorRaiseHeuristicMixed,
        PrepareBehaviorRaiseHeuristicHazard
    };

    enum RollbackBehavior
    {
        RollbackBehaviorReturn,
        RollbackBehaviorRaiseHeuristicCommit,
        RollbackBehaviorRaiseHeuristicMixed,
        RollbackBehaviorRaiseHeuristicHazard
    };

    enum CommitBehavior
    {
        CommitBehaviorReturn,
        CommitBehaviorRaiseNotPrepared,
        CommitBehaviorRaiseHeuristicRollback,
        CommitBehaviorRaiseHeuristicMixed,
        CommitBehaviorRaiseHeuristicHazard
    };

    enum CommitOnePhaseBehavior
    {
        CommitOnePhaseBehaviorReturn,
        CommitOnePhaseBehaviorRaiseHeuristicHazard,
        CommitOnePhaseBehaviorRaiseTransactionRolledback
    };

    struct ResourceBehavior
    {
        PrepareBehavior        prepare_behavior;
        RollbackBehavior       rollback_behavior;
        CommitBehavior         commit_behavior;
        CommitOnePhaseBehavior commitonephase_behavior;
    };
    typedef sequence<ResourceBehavior> ResourceBehaviorSeq;

    enum ResourceTrace
    {
        ResourceTraceUnknown,
        ResourceTraceNone,
        ResourceTracePrepare,
        ResourceTracePrepareCommit,
        ResourceTracePrepareRollback,
        ResourceTraceCommitOnePhase,
        ResourceTraceRollback,
        ResourceTracePrepareForget,
        ResourceTracePrepareCommitForget,
        ResourceTracePrepareRollbackForget,
        ResourceTraceCommitOnePhaseForget
    };

    interface Service : CosTransactions::TransactionalObject
    {
        void oper(in ResourceBehaviorSeq resource_behaviors);

        boolean       is_correct();
        ResourceTrace get_resource_trace(in long resource_number);
    };
};