/*
 * SPDX short identifier: Apache-2.0
 */


//




#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module RawSubtransactionAwareResources02
{
    enum SubtransactionAwareResourceTrace
    {
        SubtransactionAwareResourceTraceUnknown,
        SubtransactionAwareResourceTraceNone,
        SubtransactionAwareResourceTraceCommitSubtransaction,
        SubtransactionAwareResourceTraceRollbackSubtransaction
    };

    interface Service
    {
        void oper(in long subtransaction_aware_resource_number, in CosTransactions::Control ctrl);

        boolean                          is_correct();
        SubtransactionAwareResourceTrace get_subtransaction_aware_resource_trace(in long subtransaction_aware_resource_number);
    };
};