/*
 * SPDX short identifier: Apache-2.0
 */


//



#include <CosTransactions.idl>


#pragma prefix "qa.jbossts.jboss.org"




module SupportTests01
{
    exception InvocationException {};

    interface Service
    {
        void test()
            raises (InvocationException);
        boolean isCorrect()
            raises (InvocationException);
    };
};