
= Examples

== JDBC example

This simplified example assumes that you are using the transactional JDBC driver provided with {parentProduct}.
For details about how to configure and use this driver see the previous Chapter.
// Previous Chpater link?

[source,java]
----
include::{projectSourceDir}/jta/extras/jdbc_example.java[]
----

== Failure recovery example with BasicXARecovery

This class implements the `XAResourceRecovery` interface for `XAResources`.
The parameter supplied in `setParameters` can contain arbitrary information necessary to initialize the class once created.
In this example, it contains the name of the property file in which the database connection information is specified, as well as the number of connections that this file contains information on.
Each item is separated by a semicolon.

This is only a small example of the sorts of things an `XAResourceRecovery` implementer could do.
This implementation uses a property file that is assumed to contain sufficient information to recreate connections used during the normal run of an application so that recovery can be performed on them.
Typically, user-names and passwords should never be presented in raw text on a production system.

.Database parameter format for the properties file
====
----
 DB_x_DatabaseURL=
 DB_x_DatabaseUser=
 DB_x_DatabasePassword=
 DB_x_DatabaseDynamicClass=
----

`x` is the number of the connection information.
====

Some error-handling code is missing from this example, to make it more readable.

.Failure recovery example with BasicXARecovery
====
[source,java]
----
include::{projectSourceDir}/jta/extras/failure_recovery_example.java[]
----

You can use the class `com.arjuna.ats.internal.jdbc.recovery.JDBC2RecoveryConnection` to create a new connection to the database using the same parameters used to create the initial connection.
====
