
package com.jboss.jbosstm.xts.demo.theatre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-hudson-182-RC1
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITheatreServiceAT", targetNamespace = "http://www.jboss.com/jbosstm/xts/demo/Theatre")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ITheatreServiceAT {


    /**
     * 
     * @param howMany
     * @param whichArea
     */
    @WebMethod
    public void bookSeats(
        @WebParam(name = "how_many", partName = "how_many")
        int howMany,
        @WebParam(name = "which_area", partName = "which_area")
        int whichArea);

}
