/*
 * JBoss, Home of Professional Open Source
 * Copyright 2006, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. 
 * See the copyright.txt in the distribution for a full listing 
 * of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 * 
 * (C) 2005-2006,
 * @author JBoss Inc.
 */
/*
   Copyright (C) 2003, 2004
   Arjuna Technologies Limited
   Newcastle upon Tyne, UK

   $Id: Hello.idl 2342 2006-03-30 13:06:17Z  $
 */

#include <CosTransactions.idl>

/*
    The module scoping has been created to reflect the packages used within the Java source code of the Arjuna
    Transactions product trailmap.
 */
module com {
    module arjuna {
        module demo {
            module simple{
                /*
                    The Hello interface is derived from the CosTransactions::TransactionalObject. All the methods of an interface
                    derived from here automatically gain implicit transaction propogation characteristics
                 */
                interface Hello: CosTransactions::TransactionalObject
                {
                    /*
                        This will print hello to the screen under transactional control.
                        Clearly it is not a great example of what can be done transactionally (writing to the console
                        cannot be rolled back!).
                        However it suffices to illustrate that the product is correctly installed and configured.
                     */
                    void print_hello();
                };
            };
        };
    };
};
