/* This file contains SAS policy
 * $Id: SASPolicy.idl,v 1.2 2005-03-04 20:39:23 david.robison Exp $	
 */ 

#ifndef __SASPolicy_IDL
#define __SASPolicy_IDL

#include <orb.idl>

module org {
module jacorb{

// Self contained module for SAS policy

module sasPolicy {

  struct SASPolicyValues {
    short targetRequires;
    short targetSupports;
    boolean stateful;
  };

  const CORBA::PolicyType SAS_POLICY_TYPE = 102;

  local interface SASPolicy : CORBA::Policy {
    readonly attribute SASPolicyValues value;
  };

  struct ATLASPolicyValues {
    string atlasURL;
    string atlasCache;
  };

  const CORBA::PolicyType ATLAS_POLICY_TYPE = 103;

  local interface ATLASPolicy : CORBA::Policy {
    readonly attribute ATLASPolicyValues value;
  };
};

};
};
