
= Failure Recovery

The failure recovery subsystem of {parentProduct} ensure that results of a transaction are applied consistently to all resources affected by the transaction, even if any of the application processes or the hardware hosting them crash or lose network connectivity.
In the case of hardware crashes or network failures, the recovery does not take place until the system or network are restored, but the original application does not need to be restarted.
Recovery is handled by the Recovery Manager process.
For recover to take place, information about the transaction and the resources involved needs to survive the failure and be accessible afterward.
This information is held in the `ActionStore`, which is part of the `ObjectStore`.
If the `ObjectStore` is destroyed or modified, recovery may not be possible.

Until the recovery procedures are complete, resources affected by a transaction which was in progress at the time of the failure may be inaccessible.
Database resources may report this as as tables or rows held by in-doubt transactions.
For TXOJ resources, an attempt to activate the Transactional Object, such as when trying to get a lock, fails.

== Configuring the failure recovery subsystem for your ORB

Although some ORB-specific configuration is necessary to configure the ORB sub-system, the basic settings are ORB-independent.
The configuration which applies to {parentProduct} is in the `RecoveryManager-properties.xml` file and the `orportability-properties.xml` file.
Contents of each file are below.

.RecoverManager-properties.xml
[source,xml]
----
include::{projectSourceDir}/jts/extras/RecoveryManager-properties.xml[]
----

.orportability-properties.xml
[source,xml]
----
include::{projectSourceDir}/jts/extras/orportability-properties.xml[]
----

These entries cause instances of the named classes to be loaded.
The named classes then load the ORB-specific classes needed and perform other initialization.
This enables failure recovery for transactions initiated by or involving applications using this property file.
The default `RecoveryManager-properties.xml` file and `orportability-properties.xml` with the distribution include these entries.

[IMPORTANT]
Failure recovery is NOT supported with the JavaIDL ORB that is part of JDK.
Failure recovery is supported for JacOrb only.

To disable recovery, remove or comment out the `RecoveryEnablement` line in the property file.

== JTS specific recovery

=== XA resource recovery

Recovery of XA resources accessed via JDBC is handled by the `XARecoveryModule`. This module includes both transaction-initiated and resource-initiated recovery.

* Transaction-initiated recovery is possible where the particular transaction branch progressed far enough for a `JTA_ResourceRecord` to be written in the ObjectStore.
The record contains the information needed to link the transaction to information known by the rest of {parentProduct} in the database.
* Resource-initiated recovery is necessary for branches where a failure occurred after the database made a persistent record of the transaction, but before the `JTA_ResourceRecord` was written.
Resource-initiated recovery is also necessary for datasources for which it is impossible to hold information in the `JTA_ResourceRecord` that allows the recreation in the RecoveryManager of the `XAConnection` or `XAResource` used in the original application.

Transaction-initiated recovery is automatic.
The `XARecoveryModule` finds the `JTA_ResourceRecord` which needs recovery, using the two-pass mechanism described above.
It then uses the normal recovery mechanisms to find the status of the transaction the resource was involved in, by running `replay_completion` on the `RecoveryCoordinator` for the transaction branch.
Next, it creates or recreates the appropriate `XAResource` and issues `commit` or `rollback` on it as appropriate.
The `XAResource` creation uses the same database name, username, password, and other information as the application.

Resource-initiated recovery must be specifically configured, by supplying the `RecoveryManager` with the appropriate information for it to interrogate all the `XADataSources` accessed by any {parentProduct} application.
The access to each `XADataSource` is handled by a class that implements the `com.arjuna.ats.jta.recovery.XAResourceRecovery` interface.
Instances of this class are dynamically loaded, as controlled by property `JTAEnvironmentBean.xaResourceRecoveryInstances` .

The `XARecoveryModule` uses the `XAResourceRecovery` implementation to get an `XAResource` to the target datasource.
On each invocation of periodicWorkSecondPass`, the recovery module issues an `XAResource.recover` request.
This request returns a list of the transaction identifiers that are known to the datasource and are in an in-doubt state.
The list of these in-doubt Xids is compared across multiple passes, using `periodicWorkSecondPass-es`.
Any Xid that appears in both lists, and for which no `JTA_ResourceRecord` is found by the intervening transaction-initiated recovery, is assumed to belong to a transaction involved in a crash before any `JTA_Resource_Record` was written, and a `rollback` is issued for that transaction on the `XAResource`.

This double-scan mechanism is used because it is possible the Xid was obtained from the datasource just as the original application process was about to create the corresponding JTA_ResourceRecord.
The interval between the scans should allow time for the record to be written unless the application crashes (and if it does, rollback is the right answer).

An `XAResourceRecovery` implementation class can contain all the information needed to perform recovery to a specific datasource.
Alternatively, a single class can handle multiple datasources which have some similar features.
The constructor of the implementation class must have an empty parameter list, because it is loaded dynamically.
The interface includes an `initialise` method, which passes in further information as a `string`.
The content of the string is taken from the property value that provides the class name.
Everything after the first semi-colon is passed as the value of the string.
The `XAResourceRecovery` implementation class determines how to use the string.

An `XAResourceRecovery` implementation class, `com.arjuna.ats.internal.jdbc.recovery.BasicXARecovery`, supports resource-initiated recovery for any XADataSource.
For this class, the string received in method `initialise` is assumed to contain the number of connections to recover, and the name of the properties file containing the dynamic class name, the database username, the database password and the database connection URL.
The following example is for an Oracle 8.1.6 database accessed via the Sequelink 5.1 driver:

----
XAConnectionRecoveryEmpay=com.arjuna.ats.internal.jdbc.recovery.BasicXARecovery;2;OraRecoveryInfo
----

This implementation is only meant as an example, because it relies upon usernames and passwords appearing in plain text properties files.
You can create your own implementations of `XAConnectionRecovery`.
See the javadocs and the example `com.arjuna.ats.internal.jdbc.recovery.BasicXARecovery`.

.XAConnectionRecovery implementation
[source,java]
----
include::{projectSourceDir}/jts/extras/XAConnectionRecovery.java[]
----

.Multiple recovery domains and resource-initiated recovery
[NOTE]
`XAResource.recover` returns the list of all transactions that are in-doubt with in the datasource.
If multiple recovery domains are used with a single datasource, resource-initiated recovery sees transactions from other domains.
Since it does not have a `JTA_ResourceRecord` available, it rolls back the transaction in the database, if the Xid appears in successive recover calls.
To suppress resource-initiated recovery, do not supply an `XAConnectionRecovery` property, or confine it to one recovery domain.

=== Recovery behavior

Property `OTS_ISSUE_RECOVERY_ROLLBACK` controls whether the `RecoveryManager` explicitly issues a rollback request when `replay_completion` asks for the status of a transaction that is unknown.
According to the `presume-abort` mechanism used by OTS and JTS, the transaction can be assumed to have rolled back, and this is the response returned to the Resource`, including a subordinate coordinator, in this case.
The `Resource` should then apply that result to the underlying resources.
However, it is also legitimate for the superior to issue a rollback, if `OTS_ISSUE_RECOVERY_ROLLBACK` is set to `YES`.

The OTS transaction identification mechanism makes it possible for a transaction coordinator to hold a `Resource` reference that will never be usable.
This can occur in two cases:

* The process holding the `Resource` crashes before receiving the commit or rollback request from the coordinator.
* The `Resource` receives the commit or rollback, and responds.
However, the message is lost or the coordinator process has crashed.

In the first case, the `RecoveryManager` for the `Resource``ObjectStore` eventually reconstructs a new `Resource` (with a different CORBA object reference (IOR), and issues a `replay_completion` request containing the new `Resource` IOR.
The `RecoveryManager` for the coordinator substitutes this in place of the original, useless one, and issues `commit` to the new reconstructed `Resource`.
The `Resource` has to have been in a commit state, or there would be no transaction intention list.
Until the `replay_completion` is received, the `RecoveryManager` tries to send `commit` to its `Resource` reference.
This will fail with a CORBA System Exception.
Which exception depends on the ORB and other details.

In the second case, the `Resource` no longer exists.
The `RecoveryManager` at the coordinator will never get through, and will receive System Exceptions forever.

The `RecoveryManager` cannot distinguish these two cases by any protocol mechanism.
There is a perceptible cost in repeatedly attempting to send the commit to an inaccessible `Resource`. In particular, the timeouts involved will extend the recovery iteration time, and thus potentially leave resources inaccessible for longer.

To avoid this, the `RecoveryManager` only attempts to send `commit` to a `Resource` a limited number of times.
After that, it considers the transaction assumed complete.
It retains the information about the transaction, by changing the object type in the ActionStore`, and if the `Resource` eventually does wake up and a `replay_completion` request is received, the `RecoveryManager` activates the transaction and issues the commit request to the new Resource IOR.
The number of times the `RecoveryManager` attempts to issue `commit` as part of the periodic recovery is controlled by the property variable `COMMITTED_TRANSACTION_RETRY_LIMIT`, and defaults to `3`.

=== Expired entry removal

The operation of the recovery subsystem causes some entries to be made in the `ObjectStore` that are not removed in normal progress.
The `RecoveryManager` has a facility for scanning for these and removing items that are very old.
Scans and removals are performed by implementations of the `>com.arjuna.ats.arjuna.recovery.ExpiryScanner`.
Implementations of this interface are loaded by giving the class names as the value of the property `RecoveryEnvironmentBean.expiryScannerClassNames`.
The `RecoveryManager` calls the `scan` method on each loaded `ExpiryScanner` implementation at an interval determined by the property `RecoveryEnvironmentBean.expiryScanInterval`.
This value is given in hours, and defaults to `12`.
A property value of `0` disables any expiry scanning.
If the value as supplied is positive, the first scan is performed when `RecoveryManager` starts.
If the value is negative, the first scan is delayed until after the first interval, using the absolute value.

There are two kinds of item that are scanned for expiry:

[cols="1,1"]
|===

|Contact items
|
One contact item is created by every application process that uses {parentProduct}.
They contain the information that the `RecoveryManager` uses to determine if the process that initiated the transaction is still alive, and what the transaction status is.
The expiry time for these is set by the property `RecoveryEnvironmentBean.transactionStatusManagerExpiryTime`, which is expressed in hours.
The default is `12` , and `0` suppresses the expiration.
This is the interval after which a process that cannot be contacted is considered to be dead.
It should be long enough to avoid accidentally removing valid entries due to short-lived transient errors such as network downtime.

|Assumed complete transactions
|
The expiry time is counted from when the transactions were assumed to be complete.
A `replay_completion` request resets the clock.
The risk with removing assumed complete transactions it that a prolonged communication outage means that a remote `Resource` cannot connect to the `RecoveryManager` for the parent transaction.
If the assumed complete transaction entry is expired before the communications are recovered, the eventual `replay_completion` will find no information and the `Resource` will be rolled back, although the transaction committed.
Consequently, the expiry time for assumed complete transactions should be set to a value that exceeds any anticipated network outage.
The parameter is `ASSUMED_COMPLETE_EXPIRY_TIME`.
It is expressed in hours, with `240` being the default, and `0` meaning never to expire.
|===

.ExpiryScanner properties
[source,xml]
----
include::{projectSourceDir}/jts/extras/ExpiryScanner-properties.xml[]
----

There are two `ExpiryScannner`'s for the assumed complete transactions, because there are different types in the ActionStore.

=== Recovery domains

A key part of the recovery subsystem is that the `RecoveryManager` hosts the OTS `RecoveryCoordinator` objects that handle recovery for transactions initiated in application processes.
Information passes between the application process and the `RecoveryManager` in one of three ways:

* `RecoveryCoordinator` object references (IORs) are created in the application process.
They contain information identifying the transaction in the object key.
They pass the object key to the `Resource` objects, and the `RecoveryManager` receives it.
* The application process and the `RecoveryManager` access the same `jbossts-properties.xml`, and therefore use the same `ObjectStore`.
* The `RecoveryCoordinator` invokes CORBA directly in the application, using information in the contact items.
Contact items are kept in the `ObjectStore`.

Multiple recovery domains may useful if you are doing a migration, and separate `ObjectStores` are useful.
However, multiple RecoveryManagers can cause problems with XA datasources if resource-initiated recovery is active on any of them.

== Transaction status and `replay_comparison`

When a transaction successfully commits, the transaction log is removed from the system.
The log is no longer required, since all registered Resources have responded successfully to the two-phase commit sequence.
However, if a `Resource` calls `replay_completion` on the `RecoveryCoordinator` after the transaction it represents commits, the status returned is `StatusRolledback`.
The transaction system does not keep a record of committed transactions, and assumes that in the absence of a transaction log, the transaction must have rolled back.
This is in line with the `presumed abort protocol` used by the OTS.
