
= OTS and Jakarta EE Transaction Service Management

== Starting the run-time system

The {parentProduct} run-time support consists of run-time packages and the OTS transaction manager server.
By default, {parentProduct} does not use a separate transaction manager server.
Instead, transaction managers are co-located with each application process to improve performance and improve application fault-tolerance by reducing application dependency on other services.

When running applications which require a separate transaction manager, set the `JTSEnvironmentBean.transactionManager` environment variable to value `YES`.
The system locates the transaction manager server in a manner specific to the ORB being used.
This method may be any of:

* Being registered with a name server.
* Being added to the ORB’s initial references.
* Via a {parentProduct} specific references file.
* By the ORB’s specific location mechanism (if applicable).

You override the default registration mechanism by using the `OrbPortabilityEnvironmentBean.resolveService` environment variable, which takes the following values:

.Possible values of `OrbPortabilityEnvironmentBean.resolveService`
[cols="1,1"]
|===
|CONFIGURATION_FILE |This is the default, and causes the system to use the `CosServices.cfg` file.
|NAME_SERVICE |{parentProduct} attempts to use a name service to register the transaction factory. If this is not supported, an exception is thrown.
|BIND_CONNECT |{parentProduct} uses the ORB-specific bind mechanism. If this is not supported, an exception is thrown.
|RESOLVE_INITIAL_REFERENCES |{parentProduct} attempts to register the transaction service with the ORB's initial service references. If the ORB does not support this, an exception is thrown, and another option must be used.
|===

=== OTS configuration file

Similar to the `resolve_initial_references`, {parentProduct} supports an initial reference file where references for specific services can be stored and used at runtime.
The file, `CosServices.cfg`, consists of two columns: the service name (in the case of the OTS server TransactionService), and the IOR, separated by a single space.
`CosServices.cfg` is located at runtime by the following `OrbPortabilityEnvironmentBean` properties:

[cols="1,1"]
|===
|`initialReferencesRoot` |The directory where the file is located, defaulting to the current working directory.
|`initialReferencesFile` |The name of the configuration file itself, `CosServices.cfg` by default.
|===

The OTS server automatically registers itself in the `CosServices.cfg` file if the `OrbPortabilityEnvironmentBean` option is used, creating the file if necessary.
Stale information is also automatically removed.
Machines sharing the same transaction server should have access to this file, or a copy of it locally.

.Example ORB reference file settings
====
[source,xml]
----
OrbPortabilityEnvironmentBean.initialReferencesFile=myFile
OrbPortabilityEnvironmentBean.initialReferencesRoot=/tmp
----
====

=== Name service

If your ORB supports a name service, and {parentProduct} is configured to use it, the transaction manager is registered with it automatically.
There is no further work required.

// Shall we remove this?
[NOTE]
====
This option is not used for JacORB
====

// Shall we remove this?
=== resolve_initial_references

Currently, this option is only supported for JacORB.

=== Resolution services supported per ORB

[cols="1,1",options="header"]
|===
|Resolution Mechanism |ORB
|OTS configuration file |All available ORBs
|Name Service |JacORB
|resolve_initial_references |JacORB
|===

== XA Specific management

Each XA Xid that {parentProduct} creates must have a unique node identifier encoded within it.
{parentProduct} only recovers transactions and states that match a specified node identifier.
Provide the node identifier with the `CoreEnvironmentBean.nodeIdentifier` property.
This value must be unique across your {parentProduct} instances.
If you do not provide a value, {parentProduct} generates one and reports the value via the logging infrastructure.

When running XA recovery, you need to specify which types of Xid {parentProduct} can recover.
Use the `JTAEnvironmentBean.xaRecoveryNodes` property to provide one or more values, in a space-separated list.

[IMPORTANT]
====
A value of ‘*’ forces {parentProduct} to recover, and possibly rollback, all transactions, regardless of their node identifier.
Use this value with extreme caution.
====

== Selecting the JTA implementation

Two variants of the JTA implementation are now provided and accessible through the same interface.
These are:

Purely local JTA::
Only non-distributed JTA transactions can be executed.
This is the only version available with the {productName} product.

Remote, CORBA-based JTA::
Distributed JTA transactions can be executed.
This version is only available with the {parentProduct} product and requires a supported CORBA ORB.

Both of these implementations are fully compatible with the transactional JDBC driver provided with {parentProduct}.

====
.Selecting the local JTA implementation
* Set the property `JTAEnvironmentBean.jtaTMImplementation` to value `com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple`.
* Set the property `JTAEnvironmentBean.jtaUTImplementation` to value `com.arjuna.ats.internal.jta.transaction.arjunacore.UserTransactionImple`.
====

[NOTE]
====
These settings are the default values for the properties and do not need to be specified if the local implementation is required.
====

====
.Selecting the remote JTA implementation
* Set the property `JTAEnvironmentBean.jtaTMImplementation` to value `com.arjuna.ats.internal.jta.transaction.jts..TransactionManagerImple`.
* Set the property `JTAEnvironmentBean.jtaUTImplementation` to value `com.arjuna.ats.internal.jta.transaction.jts.UserTransactionImple`.
====
