/*
   Copyright The Narayana Authors
   SPDX-License-Identifier: Apache-2.0
 */

package org.jboss.jbossts.qa.junit.testgroup;

import org.jboss.jbossts.qa.junit.*;
import org.junit.*;

// Automatically generated by XML2JUnit
public class TestGroup_jdbclocals01_mysql_jndi extends TestGroup_jdbclocals01_abstract
{
	public String getTestGroupName()
	{
		return "jdbclocals01_mysql_jndi";
	}

    public String getDBName1() {
        return "DB_MYSQL_JNDI";
    }
}