/*
 * JBoss, Home of Professional Open Source
 * Copyright 2009, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2009,
 * @author JBoss Inc.
 */
package org.jboss.jbossts.qa.junit.testgroup;

import org.jboss.jbossts.qa.junit.*;
import org.junit.*;

// Automatically generated by XML2JUnit
public class TestGroup_crashrecovery13 extends TestGroupBase
{
	public String getTestGroupName()
	{
		return "crashrecovery13";
	}


	@Before public void setUp()
	{
		super.setUp();
	}

	@After public void tearDown()
	{
		try {
		} finally {
			super.tearDown();
		}
	}

	@Test public void CrashRecovery13_Test01()
	{
		setTestName("Test01");
		Task client0 = createTask("client0", org.jboss.jbossts.qa.CrashRecovery13Clients.Test01.class, Task.TaskType.EXPECT_PASS_FAIL, 240);
		client0.start("nocrash", "CR13_01.log");
		client0.waitFor();
	}

	@Test public void CrashRecovery13_Test02()
	{
		setTestName("Test02");
		Task client0 = createTask("client0", org.jboss.jbossts.qa.CrashRecovery13Clients.Test02.class, Task.TaskType.EXPECT_PASS_FAIL, 240);
		client0.start("nocrash", "CR13_02.log");
		client0.waitFor();
	}

	@Test public void CrashRecovery13_Test03()
	{
		setTestName("Test03");
		Task client0 = createTask("client0", org.jboss.jbossts.qa.CrashRecovery13Clients.Test03.class, Task.TaskType.EXPECT_PASS_FAIL, 240);
		client0.start("nocrash", "CR13_03.log");
		client0.waitFor();
	}

}