ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER dtf11 IDENTIFIED BY dtf11;
GRANT CREATE SESSION TO dtf11;
GRANT CREATE TABLE TO dtf11;
ALTER USER dtf11 QUOTA UNLIMITED ON USERS;

CREATE USER dtf12 IDENTIFIED BY dtf12;
GRANT CREATE SESSION TO dtf12;
GRANT CREATE TABLE TO dtf12;
ALTER USER dtf12 QUOTA UNLIMITED ON USERS;
