<!--
  JBoss, Home of Professional Open Source
  Copyright 2006, Red Hat Middleware LLC, and individual contributors
  as indicated by the @author tags. 
  See the copyright.txt in the distribution for a full listing 
  of individual contributors.
  This copyrighted material is made available to anyone wishing to use,
  modify, copy, or redistribute it subject to the terms and conditions
  of the GNU General Public License, v. 2.0.
  This program is distributed in the hope that it will be useful, but WITHOUT A 
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
  PARTICULAR PURPOSE.  See the GNU General Public License for more details.
  You should have received a copy of the GNU General Public License,
  v. 2.0 along with this distribution; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
  MA  02110-1301, USA.
  
  (C) 2005-2006,
  @author JBoss Inc.
-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:intf="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:impl="http://www.jboss.com/jbosstm/xts/demo/Restaurant" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant">

   <wsdl:message name="bookSeatsBARequest">

      <wsdl:part name="how_many" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="bookSeatsBAResponse">

      <wsdl:part name="bookSeatsBAResponse" type="xsd:boolean"/>

   </wsdl:message>

   <wsdl:portType name="IRestaurantServiceBA">

      <wsdl:operation name="bookSeats" parameterOrder="how_many">

         <wsdl:input name="bookSeatsBARequest" message="intf:bookSeatsBARequest"/>

         <wsdl:output name="bookSeatsBAResponse" message="intf:bookSeatsBAResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="RestaurantServiceBASoapBinding" type="intf:IRestaurantServiceBA">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="bookSeats">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="bookSeatsBARequest">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:input>

         <wsdl:output name="bookSeatsBAResponse">

            <wsdlsoap:body use="literal" namespace="http://www.jboss.com/jbosstm/xts/demo/Restaurant"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="RestaurantServiceBAService">

      <wsdl:port name="RestaurantServiceBA" binding="intf:RestaurantServiceBASoapBinding">

         <wsdlsoap:address location="http://localhost:8080/xtsdemowebservices/RestaurantServiceBA"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
