#created on: Nov 8, 2006
package com.jboss.soa.esb.routing.cbr

#list any import classes here.
import org.jboss.soa.esb.message.Message;
import org.jboss.soa.esb.message.format.MessageType;

expander XPathLanguage.dsl

#declare any global variables here
global java.util.List destinations;

rule "Routing Rule using XPATH"
	
	when xpathGreaterThan  expr "/blacktie:employee/blacktie:id", "1000" use namespaces "blacktie=http://www.jboss.org/blacktie"
	then 
	    Log : "TestOne";
		Destination : "testone";
end

rule "Routing Rule using XPATH less"
    when xpathLessThan  expr "/blacktie:employee/blacktie:id", "1000" use namespaces "blacktie=http://www.jboss.org/blacktie"
    then
	    Log : "TestTwo";
		Destination : "testtwo";
end
