name: AS_TESTS

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review, labeled, unlabeled, reopened ]
  workflow_dispatch:

jobs:
  as-test:
    name: as-tests with JDK ${{ matrix.java-version }}
    timeout-minutes: 320
    strategy:
      matrix:
        java-version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check for `testing/as-tests` label
        id: check-label
        run: |
          echo "should_skip=false" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Checking labels on PR #${{ github.event.pull_request.number }}..."
            LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            echo "Labels found: $LABELS"
            if ! echo "$LABELS" | grep -q "^testing/as-tests$"; then
              echo "Label 'testing/as-tests' not found. Skipping job."
              echo "should_skip=true" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set up JDK ${{ matrix.java-version }}
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/org/jboss
            !~/.m2/repository/org/wildfly
          key: maven-${{ runner.os }}-core
          restore-keys: |
            maven-${{ runner.os }}-

      - name: as-tests
        if: steps.check-label.outputs.should_skip != 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"  
          WORKSPACE=$PWD PROFILE=AS_TESTS ./scripts/hudson/narayana.sh
        env:
          LRA_TCK_TIMEOUT_FACTOR: 1

      - uses: actions/upload-artifact@v5
        if: steps.check-label.outputs.should_skip != 'true' && always()
        with:
          name: as-tests-logs-jdk${{ matrix.java-version }}
          path: |
            **/*.*log*
            **/ObjectStore*/**  
            **/tx-object-store/**
            **/*tx-object-store.zip
            **/target/*surefire-reports*/**
            **/target/*failsafe-reports*/**
            jboss-as/build/target/wildfly-*/**
            jboss-as/dist/target/wildfly-*.zip
            jboss-as/dist/target/wildfly-*/standalone/log/
          if-no-files-found: error