# This GitHub Action workflow automatically adds labels to a pull request based on axes found in its description.

name: Labeler

on:
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review, reopened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Label PR based on description axes
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (!prBody) {
              core.info('PR body is empty. No labels to add.');
              return;
            }

            if (prBody.includes('NO_TEST')) {
              core.info('PR description contains NO_TEST. Skipping labeling.');
              return;
            }

            const labelMap = {
              'CORE': 'testing/core',
              'AS_TESTS': 'testing/as_tests',
              'RTS': 'testing/rts',
              'JACOCO': 'testing/jacoco',
              'XTS': 'testing/xts',
              'QA_JTA': 'testing/qa_jta',
              'QA_JTS_OPENJDKORB': 'testing/qa_jts',
            };

            const labelsToAdd = [];

            // Replace "!<whitespace>" to "!" to treat "! CORE" as a single token "!CORE"
            const processedBody = prBody.replace(/!\s+/g, '!');

            // Normalize body: replace newlines/commas with spaces and split into a set of unique words (tokens)
            const tokens = new Set(processedBody.replace(/[\r\n,]/g, ' ').split(/\s+/));

            for (const [axis, label] of Object.entries(labelMap)) {
              // A label is added if the axis exists as a token AND its negated version ("!axis") does not.
              if (tokens.has(axis) && !tokens.has(`!${axis}`)) {
                labelsToAdd.push(label);
              }
            }

            // Get the names of labels already on the PR
            const existingLabelSet = new Set(context.payload.pull_request.labels.map(l => l.name));
            core.info(`Existing labels on PR: ${[...existingLabelSet].join(', ')}`);

            // Filter out labels that are already present on the PR
            const finalLabelsToAdd = labelsToAdd.filter(label => !existingLabelSet.has(label));

            // If any new labels need to be added, use the GitHub API to add them.
            if (finalLabelsToAdd.length > 0) {
              core.info(`Adding labels: ${finalLabelsToAdd.join(', ')}`);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: finalLabelsToAdd,
              });
            } else {
              core.info('No new labels to add.');
            }
